const translation = {
  Dashboard: {
    overview: "अवलोकन",
    cardOneHeading: "शेयर स्टोर लिंक",
    cardOneDescription:
      "ग्राहक निम्नलिखित लिंक पर जा सकते हैं और अपना ऑर्डर दे सकते हैं।",
    cardOneShareVia: "के माध्यम से बाँटे",
    cardTwoHeading: "कुल बिक्री",
    cardTwoPrice: "{{totalPrice}}",
    cardThreeHeading: "स्टोर दृश्य",
    cardThreeNumber: "{{totalStoreView}}",
    monthTransactions: "माह के लेन-देन",
    topSellinghProducts: "सबसे अधिक बिकने वाला उत्पाद",
    customerOfTheMonth: "ग्राहक ऑफ़ द मंथ"
  },
  SideNav: {
    dashboard: "डॅशबोर्ड",
    tableManagement: "टेबल प्रबंधन",
    billing: "बिलिंग",
    tables: "टेबल",
    transaction: "लेन-देन",
    onlineOrder: "ऑनलाईन ऑर्डर",
    product: "उत्पाद",
    productsManagement: "उत्पाद प्रबंधन",
    discountsOffers: "छूट/ऑफर",
    discount: "छूट",
    taxes: "करे",
    customers: "ग्राहक",
    customersDetails: "ग्राहक विवरण",
    brands: "ब्रांड",
    brandsDetails: "ब्रांड विवरण",
    units: "एकक",
    unitsDetails: "एकक विवरण",
    category: "वर्ग",
    categoryDetails: "वर्ग विवरण",
    salesExecutive: "विक्री कार्यकर्ता",
    salesExecutiveDetails: "विक्री कार्यकर्ता विवरण",
    storeSetting: "स्टोर सेटिंग",
    restaurantManagement: "रेस्तरां प्रबंधन",
    floor: "ज़मीन",
    table: "मेज़",
    inventoryManagement: "सूची प्रबंधन",
    stockDashboard: "स्टॉकडैशबोर्ड",
    purchaseOrder: "क्रय आदेश",
    accountSettings: "खाता/सेटिंग्स",
    language: "भाषा",
    selectLanguage: "भाषा निवडा",
    english: "English",
    arabic: "عربي",
    marathi: "मराठी",
    hindi: "हिंदी",
    "report": "रिपोर्ट",
    logout: "लॉग आउट",

  },
  TopHeader: {
    allOnlineOrders: "ऑनलाइन आदेश सम्पूर्ण",
    orderDetail: "आदेश विवरण",
    allProducts: "सभी उत्पाद",
    productDetails: "उत्पाद विवरण",
    addNewProduct: "नया उत्पाद जोड़ें",
    customerDetails: "ग्राहक विवरण",
    discountDetails: "छूट विवरण",
    taxesDetails: "कर विवरण",
    brandsDetails: "ब्रांड विवरण",
    unitsDetails: "इकाई विवरण",
    categoryDetails: "वर्ग विवरण",
    salesExecutive: "बिक्री कार्यकारी",
    loginPage: "लॉगिन पृष्ठ",
    storeSetting: "स्टोर सेटिंग",
    storeEdit: "स्टोर संपादित करें",
    billing: "बिलिंग",
    "reportDetails": "रिपोर्ट विवरण"

  },

  Tables: {
    selectTable: "मेज़ चयन करें",
    selectPlaceholderTable: "मेज़ चयन करें",
    table: "मेज़",
    occupied: "अधिग्रहित",
    newOrder: "नया आदेश",
    orderDetails: "आदेश विवरण",
    edit: "संपादित करें",
    split: "विभाजन",
    merge: "मर्ज",
    move: "मूव",
    orderNo: "आदेश संख्या",
    status: "स्थिति",
    pending: "अपूर्ण",
    category: "श्रेणी",
    dateAndTime: "तारीख और समय",
    kotHistory: "KOT इतिहास",
    srNo: "क्रमांक",
    itemName: "आइटम का नाम",
    quantity: "मात्रा",
    subtotal: "उप-योग",
    tax: "कर",
    charges: "शुल्क",
    item: "आइटम",
    total: "कुल",
    print: "प्रिंट",
    cancel: "रद्द करें",
    complete: "पूर्ण",
    selectWaiter: "सर्वर चयन करें",
    back: "वापस",
    confirm: "पुष्टि करना",
    waiter: "परिचारक",
    totalAmount: "कुल रकम",
    waiterName: "वेटर का नाम",
    date: "तारीख",
    time: "समय",
    shareReceipt: "रसीद साझा करें",
    backToTable: "टेबल पर वापस जाएं",
    receiptPreview: "रसीद पूर्वावलोकन",
    "add": "जोड़ें",
    "balance": "बैलेंस",
    "selectPaymentMethod": "भुगतान का तरीका चुनें",
    "addPaymentMethod": "भुगतान का तरीका जोड़ें",
    "paymentOptions": "भुगतान विकल्प",
    "discount": "छूट/ऑफर"
  },

  allOnlineOrder: {
    "pending": "विचाराधीन",
    "Accepted": "स्वीकृत",
    "InProgress": "प्रगति में",
    "Dispatch": "प्रेषण",
    "Delivered": "प्रदान किया गया",
    "Cancelled": "रद्द",
    // Pending: "Pending",
    // Accepted: "Accepted",
    // InProgress: "In-Progress",
    // Dispatch: "Dispatch",
    // Delivered: "Delivered",
    // Cancelled: "Cancelled",
    "CustomerName": "ग्राहक का नाम खोजें",
    "SelectStatus": "स्थिति का चयन करें",
    Back: "पीछे",
    "OrderId": "आदेश कामतत्व",
    "Date": "तारीख",
    "Customer": "ग्राहक",
    "Status": "स्थति",
    "Amount": "रकम",
    "RejectOrder": "अस्वीकृत आदेश",
    OrderID: "आदेश कामतत्व ",
    OrderStatus: "आदेश की स्थिति ",
    OrderBookingTime: "ऑर्डर बुकिंग का समय ",
    Item: "वस्तु",
    Discount: "छूट ",
    ItemPrice: "आइटम की कीमत ",
    Notes: "टिप्पणियाँ",
    Addordernoteshere: "यहां ऑर्डर नोट जोड़ें",
    ADD: "जोड़ें",
    ItemTotal: "आइटम का कुल",
    Delivery: "डिलिव्हरी",
    GrandTotal: "कुल योग",
    Customerdetails: "ग्राहक विवरण",
    Name: "नाम:",
    Mobile: "मोबाइल:",
    Address: "पता:",
    City: "शहर:",
    State: "राज्य:",
    Postcode: "पोस्टकोड:",
    Payment: "भुगतान:",
    CurrentStatus: "वर्तमान स्थिति",
    Delivery: "डिलिव्हरी",
    noteOne: "आपके पास नहीं है",
    noteTwo: "अधिक ऑर्डर प्राप्त करने के लिए सोशल मीडिया पर अपने ग्राहकों के साथ अपने स्टोर का लिंक साझा करें।",
    free: "मुक्त",
    onlineOrders: "ऑनलाइन ऑर्डर"
  },

  CustomerDetails: {
    search: "ग्राहक के नाम से खोजें",
    addCustomers: "+ ग्राहकों को जोड़ें",
    editCustomer: "ग्राहक विवरण संपादित करें",
    customersName: "ग्राहक का नाम",
    email: "ईमेल",
    contactNo: "संपर्क नंबर",
    address: "पता",
    city: "शहर",
    country: "देश",
    "addCustomer": "ग्राहक जोड़ें +",
    "name": "नाम",
    "emailAddress": "ईमेल पता",
    "mobileNumber": "मोबाइल नंबर",
    "submit": "जमा करें",
    enterCustomerName: "ग्राहक नाम दर्ज करें",
    enterCustomerEmail: "ग्राहक ईमेल दर्ज करें",
    enterMobileNumber: "मोबाइल नंबर दर्ज करें",
    enterAddress: "पता दर्ज करें",
    enterCity: "शहर दर्ज करें",
    enterCountry: "अपने देश का नाम दर्ज करें",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    customersList: "ग्राहकों की सूची",
    totalCustomerCount: "कुल ग्राहक संख्या",
    newCustomerCount: "नई ग्राहक संख्या",
    customerOftheMonth: "महीने का ग्राहक"
  },
  DiscountDetails: {
    search: "खोज...",
    "createCoupon": "कूपन बनाएं",
    "discount": "छूट",
    "startDate": "प्रारंभ तिथि",
    "endDate": "समाप्ति तिथि",
    Expire: "समय सीमा समाप्त",
    "removediscount": "छूट निकालें",
    "applyDiscount": "छूट लागू करें",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    "submit": "जमा करें",
    "discountName": "छूट का नाम",
    "discountValue": "छूट की मान",
    "addDiscount": "छूट जोड़ें",
    editDiscount: "छूट संपादित करें",
    "enterDiscountValue": "छूट मान दर्ज करें",
    "productName": "उत्पाद नाम",
    "beforeDiscount": "छूट से पहले",
    "afterDiscount": "छूट के बाद",
    "removeDiscountFromProduct": "उत्पाद से हटाएँ",
    "applyDiscountOnProduct": "उत्पाद पर लगाएं",
    discountTableHeading: "सवलत यादी",
    SearchProductByName: "नाम से उत्पाद खोजें",
    selectedDiscount: "चयनित छूट",
    selectCategory: "श्रेणी चुनना",
    RemoveMappedDiscount: "मैप्ड छूट हटाएँ",
    SearchDiscountName: "छूट के नाम से खोजें",
  },
  TaxDetails: {
    search: "खोज...",
    addTax: "कर जोड़ें +",
    tax: "कर",
    taxes: "करें",
    values: "कर मूल्य",
    removeTax: "कर हटाएं",
    applyTax: "कर लागू करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    removeTaxFromProduct: "उत्पाद से कर हटाएं",
    applyTaxOnProduct: "उत्पाद पर कर लागू करें",
    submit: "जमा करें",
    editTax: "कर संपादित करें",
    taxName: "कर नाम",
    taxValueInPercent: "कर मूल्य % में",
    enterTaxValue: "कर मूल्य दर्ज करें",
    productName: "उत्पाद नाम",
    beforeTax: "कर से पहले",
    afterTax: "कर के बाद",
    remove: "हटाओ",
    apply: "आवेदन करना",
    taxTableHeading: "कर सूची",
    selectedTax: "चयनित कर",
    removeMappedTax: "मैप्ड टैक्स हटाएं",
    searchTaxName: "कर नाम से खोजें",

  },

  BrandDetails: {
    "search": "शोध...",
    "brand": "ब्रैंड",
    brandPlaceholder: "ब्रांड नाम दर्ज करें",
    "addBrands": "ब्रांड जोड़ें +",
    editBrands: "ब्रांड संपादित करें",
    "brandName": "ब्रांड का नाम",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    "submit": "जमा करें",
    brandList: "ब्रांड सूची",
    searchBrandName: "ब्रांड नाम से खोजें",
  },

  UnitDetails: {
    "search": "इकाई नाम से खोजें",
    "unit": "युनिट",
    "addUnit": "यूनिट जोड़ें +",
    "editUnit": "यूनिट संपादित करें",
    "unitPlaceholder": "इकाई का नाम दर्ज करें",
    "unitName": "यूनिट का नाम",
    "submit": "जमा करें",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    "isMeasurable": "दयनीय है",
    unitList: "इकाइयों की सूची"
  },

  AllProduct: {
    product: "उत्पाद",
    showExpireBefore: "समाप्ति तिथि निर्धारित करें",
    searchProducts: "उत्पाद के नाम से खोजें",
    uploadBulk: "बड़े मात्रा में अपलोड करें",
    addNewProduct: "नया उत्पाद जोड़ें",
    productId: "उत्पाद आईडी",
    InventoryManage: "इन्वेंटरी प्रबंधन",
    sellingPrice: "विक्रय मूल्य",
    expiryDate: "समाप्ति तिथि",
    Expire: "समय सीमा समाप्त",
    status: "स्थिति",
    action: "कार्रवाई",
    availableQuantity: "उपलब्ध मात्रा",
    fileUpload: "फ़ाइल अपलोड करें",
    lineOne: "कृपया डाउनलोड बटन पर क्लिक करें और एक्सेल फ़ाइल डाउनलोड करें",
    lineTwo: "फिर एक्सेल फ़ाइल को संपादित करें",
    lineThree: "और अपने स्टोर के उत्पादों की कीमत अपडेट करें",
    lineFour: "फिर अपलोड पूरा होने के बाद, अपने POS पर जाएं,",
    lineFive: "ऐप और बैकअप/उत्पाद डैशबोर्ड पर जाएं",
    lineSix: "केवल xml या xlsm फ़ाइल स्वरूप अपलोड करें",
    clickToDownload: "डाउनलोड करने के लिए क्लिक करें",
    upload: "अपलोड करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    allProducts: "सभी प्रोडक्ट",
    Back: "पीछे",
    quantity: "मात्रा",
    valid: "वैध",
    expired: "खत्म हो चुका",
    Instock: "स्टॉक में",
    outofstock: "स्टॉक ख़त्म",
    selectcategory: "श्रेणी चुनना",
    Yes: "हाँ",
    No: " नहीं",
    addQuantity: "मात्रा जोड़ें",
    add: "जोड़ना",
    addInventory: "सूची जोड़ें",
    purchasePrice: "खरीद मूल्य",
    enterPurchasePrice: "खरीद मूल्य दर्ज करें",
    purchaseDate: "खरीद तारीख",
    notes: "टिप्पणियाँ",
    enterNotes: "टिप्पणियाँ दर्ज करें",
    update: "अद्यतन",



  },
  AddNewProduct: {
    productCreation: "उत्पाद निर्माण",
    productInformation: "उत्पाद जानकारी",
    productEdit: "उत्पाद संपादन",
    uploadImage: "छवि अपलोड करें",
    preview: "पूर्वावलोकन",
    setDefault: "डिफ़ॉल्ट सेट करें",
    notAllowedBeforeUpload: "अपलोड से पहले अनुमति नहीं है",
    productName: "उत्पाद का नाम",
    enterValidName: "वैध नाम दर्ज करें",
    unit: "उत्पाद इकाई",
    enterValidUnit: "वैध यूनिट दर्ज करें",
    addUnit: "यूनिट जोड़ें",
    sellingPrice: "उत्पाद बेचने की कीमत",
    productSellingPrice: "उत्पाद बेचने की कीमत दर्ज करें",
    productDescription: "उत्पाद विवरण",
    pleaseEnterProductDescription: "कृपया उत्पाद विवरण दर्ज करें",
    minimumThreeRows: "न्यूनतम 3 पंक्तियाँ",
    purchasingPrice: "खरीदारी की कीमत",
    mrp: "एमआरपी",
    category: "श्रेणी",
    selectCategory: "श्रेणी का चयन करें",
    addCategory: "श्रेणी जोड़ें",
    brand: "ब्रांड",
    selectBrand: "ब्रांड का चयन करें",
    addBrand: "ब्रांड जोड़ें",
    barcode: "बारकोड",
    inventoryManage: "इन्वेंटरी प्रबंधित करें",
    quantity: "मात्रा",
    expiryDate: "समाप्ति तिथि",
    applyTax: "टैक्स लागू करें",
    selectTax: "टैक्स का चयन करें",
    addTax: "टैक्स जोड़ें",
    taxInclude: "टैक्स शामिल करें",
    applyDiscount: "डिस्काउंट लागू करें",
    addDiscount: "डिस्काउंट जोड़ें",
    selectDiscount: "डिस्काउंट का चयन करें",
    updateProduct: "उत्पाद अपडेट करें",
    addProduct: "उत्पाद जोड़ें",
    moreOption: "अधिक विकल्प",
    "hideOption": "विकल्प छुपाएं",
    productUnit: "उत्पाद इकाई",
    selectUnit: "इकाई का चयन करें",
    purchasingPriceOfProduct: "उत्पाद का क्रय मूल्य",
    productMRP: "उत्पाद एमआरपी",
    productBarcode: "उत्पाद बारकोड",
    stockLevelAlert: "स्टॉक लेवल अलर्ट",
    submit: "जमा करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    update: "अद्यतन",
    Back: "पीछे",
    editInventory: "इन्वेंटरी संपादित करें"

  },
  Billing: {
    selectSalesExecutive: "विक्रय कार्यकारी चुनें",
    searchProducts: "उत्पाद खोजें...",
    searchSalesExecutive: "बिक्री कार्यकारी खोजें...",
    searchCustomer: "ग्राहक खोजें...",
    select: "चुनें",
    expiredProduct: "समाप्त हो गया उत्पाद",
    productExpiring: "समाप्ति उत्पाद",
    applyDiscount: "डिस्काउंट लागू करें",
    productExpiryClickHere: "उत्पाद समाप्ति दिनांक यहां क्लिक करें",
    productName: "उत्पाद का नाम",
    mrp: "एमआरपी",
    sellingPrice: "बिक्री कीमत",
    price: "कीमत",
    quantity: "मात्रा",
    remove: "हटाएं",
    emptyCart: "खाली कार्ट",
    customer: "ग्राहक",
    change: "बदलें",
    salesExecutive: "विक्रय कार्यकारी",
    tax: "कर",
    discount: "डिस्काउंट",
    applyAdditionalDiscount: "अतिरिक्त डिस्काउंट लागू करें",
    flateDiscount: "फ्लैट डिस्काउंट",
    total: "कुल",
    fastPay: "फास्टपे",
    selectCustomer: "ग्राहक का चयन करें",
    selectDiscount: "छूट का चयन करें",
    afterDiscount: "छूट के बाद",
    selectPaymentMode: "भुगतान मोड का चयन करें",
    putOnHold: "होल्ड पर रख दें",
    submit: "जमा करें",
    clearCart: "कार्ट को खाली करें",
    paymentSuccess: "भुगतान की सफलता!",
    customerName: "ग्राहक का नाम",
    orderId: "आदेश कामतत्व",
    totalAmount: "कुल राशि",
    paymentType: "भुगतान प्रकार",
    salesExecutiveName: "बिक्री कार्यकारी का नाम",
    remove: "निकालना",
    pullBack: "ठहराना",
    clearCart: "कार्ट को खाली करें",
    save: "बचाना",
    sendToKOT: "KOT को भेजें",
    item: "वस्तु",
    table: "मेज़",
    removeTable: "मेज़ हटाएं",
    products: "उत्पादों",
    chooseCategory: "श्रेणी का चयन करें"

  },
  FloorDetails: {
    search: "मंजिल के नाम से खोजें",
    addFloor: "मंजिल जोड़ें +",
    editFloor: "मंजिल संपादित करें",
    name: "नाम",
    location: "स्थान",
    tableCount: "मेज की संख्या",
    date: "तारीख",
    edit: "संपादित करें",
    delete: "हटाएं",
    submit: "जमा करें",
    namePlaceholder: "तल का नाम दर्ज करें",
    locationPlaceholder: "स्थान का नाम दर्ज करें",
    floorPlan: "फ़्लोर प्लान",
    editFloorPlan: "फ़्लोर प्लान संपादित करें",
    height: "ऊचाई",
    width: "चौड़ाई",
    noOfSeats: "सीटों की संख्या:",
    floorList: "मंजिल सूची"



  },
  TableDetails: {
    search: "मेज़ नाम से खोजें",
    addTable: "मेज़ जोड़ें +",
    editTable: "मेज़ संपादित करें",
    tableName: "मेज़ का नाम",
    capacity: "मेज़ क्षमता",
    date: "तारीख",
    edit: "संपादित करें",
    delete: "हटाएं",
    submit: "जमा करें",
    selectFloor: "तल चयन करें",
    tableNamePlaceholder: "मेज़ का नाम दर्ज करें",
    capacityPlaceholder: "मेज़ सीटिंग क्षमता दर्ज करें",
    tableList: "मेज़ सूची"
  },
  StockDashboard: {
    poNumber: "PO नंबर",
    status: "स्थिति",
    updated: "अपडेट किया गया",
    expectedOn: "पर आशितित",
    vendor: "विक्रेता",
    destination: "स्थान",
    amount: "रकम",
    actions: "क्रियाएँ",
    notes: "टिप्पणियाँ",
    productName: "उत्पाद का नाम",
    purchasingPrice: "खरीद मूल्य",
    lastUpdated: "अंतिम अपडेट",
    quantity: "मात्रा",
    inventoryId: "सूची पहचान"
  },

  PurchaseOrderPage: {
    vendor: "विक्रेता",
    vendorPlaceholder: " विक्रेता चयन करें",
    shipTo: "शिप टू",
    shipToPlaceholder: "चयन करें",
    poNumber: "PO नंबर",
    poInvoiceNumber: "PO चालान नंबर",
    expectedDelivery: "अपेक्षित वितरण",
    billingDate: "भुगतान करने की तारीख",
    applyTaxAfterDiscount: "सवारी के बाद कर लागू करें",
    notes: "टिप्पणियाँ",
    addItem: "आइटम जोड़ें",
    srNo: "क्रमांक",
    productName: "उत्पाद का नाम",
    unitBuyingPrice: "यूनिट खरीद मूल्य",
    unitBasePrice: "यूनिट बेस मूल्य",
    unitSellingPrice: "यूनिट विक्रय मूल्य",
    unitBasePriceWithoutTax: "यूनिट बेस मूल्य (बिना कर के)",
    unitBuyingPriceWithTax: "यूनिट खरीद मूल्य (कर सहित)",
    mrp: "एमआरपी",
    quantity: "मात्रा",
    discount: "छूट",
    tax: "कर",
    actions: "क्रियाएँ",
    calculateUnitBuyingPrice: "यूनिट खरीद मूल्य की गणना करें.",
    discountType: "छूट प्रकार",
    discountValue: "छूट मूल्य",
    percentage: "प्रतिशत",
    flat: "समतल",
    namePlaceholder: "उत्पाद चयन करें",
    taxPlaceholder: "कर चयन करें",
    discountPlaceholder: "प्रकार चयन करें",
    createItem: "आइटम बनाएं",
    submit: "जमा करें",
    poNumberPlaceholder: 'पीओ नंबर दर्ज करें',
    poInvoicePlaceholder: 'पीओ इनवॉइस नंबर दर्ज करें'

  },
  AccountAndSettings: {
    posSetting: "POS सेटिंग",
    invoiceSettings: "चालान सेटिंग्स",
    invoiceSize: "चालान का आकार",
    preview: "पूर्वावलोकन",
    sizePlaceholder: "चालान का आकार चयन करें",

  },
  CategoryDetails: {
    "search": "श्रेणी के नाम से खोजें",
    "addCategory": "+ श्रेणी जोड़ें",
    "editCategory": "श्रेणी संपादित करें",
    "category": "श्रेणी",
    "inputText": "कैटेगरी के लिए यहां टाइप करें",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    "submit": "जमा करें",
    categoryList: "श्रेणी सूची"
  },
  SalesExecutive: {
    search: "बिक्री कार्यकारी नाम से खोजें",
    addSalesExecutive: "+ बिक्री कार्यकारी जोड़ें",
    salesExecutive: "सेल्स एक्झिक्युटिव्ह",
    activeInactive: "सक्रिय/निष्क्रिय",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    setOnDuty: "ड्यूटी पर लगाओ",
    addSalesExecutiveName: "बिक्री कार्यकारी नाम जोड़ें",
    editSalesExecutiveName: "बिक्री कार्यकारी नाम संपादित करें",
    salesExecutiveName: "बिक्री कार्यकारी का नाम",
    enterSalesExecutiveName: "बिक्री कार्यकारी नाम दर्ज करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    submit: "जमा करें",
    salesExcutiveList: "सेल्सएक्सक्यूटिव सूची"

  },
  StoreSetting: {
    storeDetails: "स्टोर विवरण",
    storeName: "दुकान का नाम",
    storeId: "दुकान आईडी",
    currency: "मुद्रा",
    gst: "जीएसटी",
    deliveryDetails: "वितरण विवरण",
    homeDelivery: "घर तक वितरण",
    minimumOrderLimit: "न्यूनतम ऑर्डर सीमा",
    freeDeliveryWithin: "फ्री डिलीवरी के अंदर",
    storeTiming: "स्टोर टाइमिंग",
    storeOpeningTime: "दुकान खुलने का समय",
    storeClosingTime: "दुकान बंद होने का समय",
    storeCloseDay: "दुकान बंद दिन",
    address: "पता",
    area: "क्षेत्र",
    city: "शहर",
    pincode: "पिनकोड",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    contact: "संपर्क",
    mobile: "मोबाइल",
    emailId: "ईमेल आईडी",
    customerID: "ग्राहक आईडी",
    editStore: "स्टोर को संपादित करें",
    licenseDetails: "लाइसेंस विवरण",
    licenseKey: "लाइसेंस कुंजी",
    status: "स्थिति",
    expiryDate: "समाप्ति तिथि",
    remainigDate: "शेष दिन"



  },
  StoreEdit: {
    storeInformation: "दुकान की जानकारी",
    storeId: "स्टोर आईडी",
    storeName: "स्टोर का नाम",
    currency: "मुद्रा",
    gst: "जीएसटी",
    deliveryDetails: "वितरण विवरण",
    minimumOrderLimit: "न्यूनतम ऑर्डर सीमा",
    deliveryCharge: "डिलीवरी शुल्क",
    freeDeliveryWithin: "फ्री डिलीवरी के साथ",
    storeTiming: "स्टोर टाइमिंग",
    storeOpeningTime: "स्टोर खोलने का समय",
    storeClosingTime: "स्टोर बंद करने का समय",
    storeCloseDay: "दुकान बंद दिन",
    address: "पता",
    city: "शहर",
    pincode: "पिन कोड",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    area: "क्षेत्र",
    changeAddress: "पता बदलें",
    updateStore: "स्टोर अपडेट करें",
    mapAddress: "आपकी दुकान को ऑनलाइन सेटअप करने के लिए हमें आपके स्टोर का पता चाहिए",
    next: "अगला",
    back: "पीछे",
    homeDeliveryAvailable: "होम डिलीवरी उपलब्ध",
    cancel: "रद्द"

  },
  addStore: {
    "AddStore": "दुकान जोड़ें",
    "AddressConfirmation": "पता पुष्टि",
    "ShopNo": "दुकान संख्या, गली संख्या, इमारत संख्या आदि",
    // "Selectedaddressonmap": "नक्शे पर चयनित पता",
    "Selectedaddressonmap": "पता",
    "State": "राज्य",
    "Pincode": "पिन कोड",
    "Country": "देश",
    "USETHISADDRESS": "इस पते का उपयोग करें",
    "StoreSummary": "दुकान सारांश",
    "StoreName": "दुकान का नाम",
    "StoreCategory": "दुकान श्रेणी",
    "StoreCurrency": "दुकान मुद्रा",
    "StoreAddress": "दुकान का पता",
    "CREATESTORE": "दुकान बनाएं",
    "City": "शहर",
    "EnterStoreName": "दुकान का नाम दर्ज करें",
    "SelectCountry": "देश का चयन करें",
    "SelectStoreType": "स्टोर के प्रकार का चयन करें",
    "ChooseAddressUsingMap": "मानचित्र का उपयोग करके पता चुनें",
    "NEXT": "आगे बढ़ें",
    "Back": "पीछे",
    "Mobile": "मोबाईल",
    "mobileplaceholder": "कृपया मोबाइल नंबर दर्ज करें",
    "StoreNotes": "हमें आपकी ओर से कुछ विवरणों की आवश्यकता है ताकि आप इस अद्भुत ऐप के साथ आरंभ कर सकें।",
    "WelcomeNotes": "Ezy POS में आपका स्वागत है",
  },
  Report: {
    selectCustomDate: "कस्टम तिथि का चयन करें",
    search: "शोध...",
    selectMonth: "महीना चुनें",
    getReport: "रिपोर्ट ले लो",
    date: "तारीख",
    total: "कुल",
    details: "विवरण",
    startDate: "शुरुआत तिथि",
    endDate: "अंतिम तिथि",
    emptyPageNote: "रिपोर्ट के लिए कृपया तिथि या महीना चुनें",
    showChart: "चार्ट दिखाएँ",
    reportTransactionChart: "रिपोर्ट लेनदेन चार्ट",
    customer: "ग्राहक",
    paymentMode: "भुगतान का मोड़",
    paymentId: "भुगतान आईडी",
    viewOrder: "ऑर्डर देखें",
    products: "उत्पाद",
    quantity: "मात्रा",
    discount: "डिस्काउंट",
    tax: "कर",
    transactionsReportDetails: "लेन-देन रिपोर्ट विवरण"


  },

  Transaction: {
    "transactionPleaseSelectDate": "लेन-देन कृपया तिथि चुनें",
    "search": "लेनदेन खोजें",
    "selectCustomDate": "कस्टम तिथि का चयन करें",
    "paymentType": "भुगतान प्रकार",
    "servedBy": "द्वारा सेवा",
    "paymentId": "भुगतान आईडी",
    "customer": "ग्राहक",
    "date": "तारीख",
    "total": "कुल",
    "endDate": "अंतिम तिथि",
    "startDate": "शुरुआत तिथि",
    "find": "find",
    "today": "आज",
    "last7Days": "पिछले 7 दिन",
    "last30Days": "पिछले 30 दिनों में",
    "last3Month": "पिछले 3 महीने",
    "last6Month": "पिछले 6 महीने",
    "transactionInLast": "अंत में लेन-देन",
    "transactionDetails": "लेनदेन का विवरण",
    "selectMonth": "महीना चुनिए",
    "transaction": "लेन-देन",
    transactionList: "लेनदेन सूची",
    selectSalesExecutive: "सेल्सएग्जीक्यूटिव का चयन करें"

  },

  SingleTransaction: {
    "products": "उत्पादों",
    "quantity": "मात्रा",
    "total": "कुल",
    "tax": "कर",
    "discount": "डिस्काउंट"
  },

  trailNotification: {
    ThereAre: "आपकी प्रशिक्षण में",
    leftOnYourTrail: "बचे हैं।",
    clickHereToUpgrade: "अपग्रेड के लिए यहाँ क्लिक करें",
    UpgradeToUnlockThisFeature: "इस सुविधा को अनलॉक करने के लिए अपग्रेड करें",
    Upgrade: "अपग्रेड",
    day: "दिन",
    days: "दिन",
    freeTrialPlan: "निःशुल्क परीक्षण योजना"
  }







};

export default translation;
