const translation = {
  Dashboard: {
    overview: "ملخص",
    cardOneHeading: " مشاركة رابط المتجر",
    cardOneDescription: "يمكن للعملاء زيارة الرابط التالي وضع طلباتهم.",
    cardOneShareVia: "مشاركة عبر",
    cardTwoHeading: "المبيعات الإجمالية",
    cardTwoPrice: "{{totalPrice}}",
    cardThreeHeading: "عرض المتجر",
    cardThreeNumber: "{{totalStoreView}}",
    monthTransactions: "معاملات الشهر",
    topSellinghProducts: "المنتج الأكثر مبيعا",
    customerOfTheMonth: "عميل الشهر"
  },
  SideNav: {
    dashboard: "لوحة التحكم",
    tableManagement: "إدارة الجدول",
    billing: "الفواتير",
    tables: "الجداول",
    transaction: "عملية",
    onlineOrder: "أمر عبر الإنترنت",
    product: "منتج",
    productsManagement: "إدارة المنتجات",
    discountsOffers: "خصومات/عروض",
    discount: "خصم",
    taxes: "ضرائب",
    customers: "العملاء",
    customersDetails: "تفاصيل العملاء",
    brands: "العلامات التجارية",
    brandsDetails: "تفاصيل العلامات التجارية",
    units: "وحدات",
    unitsDetails: "تفاصيل الوحدات",
    category: "الفئة",
    categoryDetails: "تفاصيل الفئة",
    salesExecutive: "المندوب المبيعات",
    salesExecutiveDetails: "تفاصيل المندوب المبيعات",
    storeSetting: "إعدادات المتجر",
    restaurantManagement: "إدارة المطعم",
    floor: "الطابق",
    table: "الطاولة",
    inventoryManagement: "إدارة المخزون",
    stockDashboard: "لوحة المخزون",
    purchaseOrder: "أمر الشراء",
    accountSettings: "الحساب/الإعدادات",
    language: "لغة",
    selectLanguage: "اختار اللغة",
    english: "English",
    arabic: "عربي",
    marathi: "मराठी",
    hindi: "हिंदी",
    "report": "تقرير",
    logout: "تسجيل الخروج",

  },
  TopHeader: {
    allOnlineOrders: "جميع الطلبات عبر الإنترنت",
    orderDetail: "تفاصيل الطلب",
    allProducts: "جميع المنتجات",
    productDetails: "تفاصيل المنتج",
    addNewProduct: "إضافة منتج جديد",
    customerDetails: "تفاصيل العملاء",
    discountDetails: "تفاصيل الخصم",
    taxesDetails: "تفاصيل الضرائب",
    brandsDetails: "تفاصيل العلامات التجارية",
    unitsDetails: "تفاصيل الوحدات",
    categoryDetails: "تفاصيل الفئة",
    salesExecutive: "المندوب المبيعات",
    loginPage: "صفحة تسجيل الدخول",
    storeSetting: "إعدادات المتجر",
    storeEdit: "تحرير المتجر",
    billing: "الفواتير",
    "reportDetails": "تفاصيل التقرير"
  },
  Tables: {
    selectTable: "اختر الطاولة",
    selectPlaceholderTable: "اختر الطاولة",
    table: "الطاولة",
    occupied: "محجوزة",
    newOrder: "طلب جديد",
    orderDetails: "تفاصيل الطلب",
    edit: "تحرير",
    split: "تقسيم",
    merge: "دمج",
    move: "تحريك",
    orderNo: "رقم الطلب",
    status: "الحالة",
    pending: "قيد الانتظار",
    category: "الفئة",
    dateAndTime: "التاريخ والوقت",
    kotHistory: "تاريخ KOT",
    srNo: "الرقم التسلسلي",
    itemName: "اسم العنصر",
    quantity: "الكمية",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    charges: "الرسوم",
    item: "العنصر",
    total: "المجموع",
    print: "طباعة",
    cancel: "إلغاء",
    complete: "اكتمل",
    selectWaiter: "اختر النادل",
    back: "خلف",
    confirm: "يتأكد",
    waiter: "النادل",
    totalAmount: "المبلغ الإجمالي",
    waiterName: "اسم الجار",
    date: "تاريخ",
    time: "الوقت",
    shareReceipt: "مشاركة الفاتورة",
    backToTable: "العودة إلى الطاولة",
    receiptPreview: "معاينة الاستلام",
    "add": "إضافة",
    "balance": "الرصيد",
    "selectPaymentMethod": "اختيار طريقة الدفع",
    "addPaymentMethod": "إضافة وسيلة دفع",
    "paymentOptions": "خيارات الدفع",
    discount: "خصم"
  },
  allOnlineOrder: {
    pending: "معلق",
    Accepted: "مقبول",
    InProgress: "جاري التنفيذ",
    Dispatch: "الإرسال",
    Delivered: "تم التسليم",
    Cancelled: "ألغيت",
    // Pending: "Pending",
    // Accepted: "Accepted",
    // InProgress: "In-Progress",
    // Dispatch: "Dispatch",
    // Delivered: "Delivered",
    // Cancelled: "Cancelled",
    CustomerName: "االبحث عن اسم العميل",
    SelectStatus: "حدد الحالة",
    Back: "خلف",
    OrderId: "رقم التعريف الخاص بالطلب",
    Date: "تاريخ",
    Customer: "عميل",
    Status: "حالة",
    Amount: "كمية",
    RejectOrder: "رفض الطلب",
    OrderID: "رقم التعريف الخاص بالطلب ",
    OrderStatus: "حالة الطلب  ",
    OrderBookingTime: "طلب وقت الحجز  ",
    Item: "غرض",
    Discount: "تخفيض ",
    ItemPrice: "سعر العنصر ",
    Notes: "ملحوظات",
    Addordernoteshere: "أضف ملاحظات الطلب هنا",
    ADD: "يضيف",
    ItemTotal: "مجموع الاشياء",
    Delivery: "توصيل",
    GrandTotal: "المجموع الإجمالي",
    Customerdetails: "تفاصيل العميل",
    Name: "الاسم:",
    Mobile: "الجوال:",
    Address: "العنوان:",
    City: "المدينة:",
    State: "الولاية:",
    Postcode: "الرمز البريدي:",
    Payment: "الدفع:",
    CurrentStatus: "الحالة الحالية",
    Delivery: "توصيل",
    noteOne: "ليس لديك أي منها",
    noteTwo: "شارك رابط متجرك مع عملائك على وسائل التواصل الاجتماعي للحصول على المزيد من الطلبات",
    free: "حر",
    onlineOrders: "الطلبات عبر الإنترنت"

  },
  CustomerDetails: {
    "search": "البحث حسب اسم العميل",
    "addCustomers": "إضافة العملاء +",
    "editCustomer": "تحرير تفاصيل العميل",
    "customersName": "اسم العميل",
    "email": "بريد إلكتروني",
    "contactNo": "رقم الاتصال",
    "address": "عنوان",
    "city": "مدينة",
    "country": "بلد",
    "addCustomer": "أضف الزبون",
    "name": "الاسم",
    "emailaddress": "عنوان البريد الإلكتروني",
    "mobileNumber": "رقم الجوال",
    "submit": "إرسال",
    enterCustomerName: "أدخل اسم العميل",
    enterCustomerEmail: "أدخل البريد الإلكتروني للعميل",
    enterMobileNumber: "أدخل رقم الهاتف المحمول",
    enterAddress: "أدخل العنوان",
    enterCity: "أدخل اسم المدينة",
    enterCountry: "أدخل اسم بلدك",
    "edit": "تعديل",
    "delete": "حذف",
    customersList: "قائمة العملاء",
    totalCustomerCount: "إجمالي عدد العملاء",
    newCustomerCount: "مجلس العملاء الجديد",
    customerOftheMonth: "عميل الشهر"

  },

  DiscountDetails: {
    "search": "بحث...",
    "createCoupon": "إنشاء كوبون",
    "discount": "خصم",
    "startDate": "تاريخ البدء",
    "endDate": "تاريخ الانتهاء",
    "Expire": "تنقضي",
    "removeDiscount": "إزالة الخصم",
    "applyDiscount": "تطبيق الخصم",
    "edit": "تحرير",
    "delete": "حذف",
    "submit": "إرسال",
    "discountName": "خصم الاسم",
    "discountValue": "قيمة الخصم",
    "addDiscount": "إضافة الخصم",
    editDiscount: "تحرير الخصم",
    "enterDiscountValue": "أدخل قيمة الخصم",
    "productName": "اسم المنتج",
    "beforeDiscount": "قبل الخصم",
    "afterDiscount": "بعد الخصم",
    "removeDiscountFromProduct": "إزالة من المنتج",
    "applyDiscountOnProduct": "تنطبق على المنتج",
    discountTableHeading: "قائمة الخصم",
    SearchProductByName: "البحث عن المنتج بالاسم",
    selectedDiscount: "الخصم المحدد",
    selectCategory: "اختر الفئة",
    RemoveMappedDiscount: "إزالة الخصم المعين",
    SearchDiscountName: "البحث حسب اسم الخصم",
    selectedTax: "الضريبة المختارة",
    removeMappedTax: "إزالة الضريبة المعينة",

  },

  TaxDetails: {
    "search": "بحث...",
    "addTax": "+ أضف ضريبة",
    tax: "ضريبة",
    "taxes": "الضرائب",
    values: "قيمة الضريبة",
    "removeTax": "إزالة الضريبة",
    "applyTax": "تطبيق الضريبة",
    "edit": "تعديل",
    "delete": "حذف",
    "removeTaxFromProduct": "إزالة التكسير من المنتج",
    "applyTaxOnProduct": "تطبيق الضريبة على المنتج",
    "submit": "إرسال",
    "editTax": "تحرير الضرائب",
    "taxName": "الاسم الضريبي",
    "taxValueInPercent": "قيمة الضريبة بالنسبة المئوية",
    "enterTaxValue": "أدخل قيمة الضريبة",
    "productName": "اسم المنتج",
    "beforeTax": "قبل الضرائب",
    "afterTax": "بعد الضريبه",
    "remove": "يزيل",
    apply: "يتقدم",
    taxTableHeading: "قائمة الضرائب",
    searchTaxName: "البحث حسب الاسم الضريبي"

  },

  BrandDetails: {
    "search": "بحث...",
    "brand": "ماركة",
    brandPlaceholder: "أدخل اسم العلامة التجارية",
    "addBrands": "أضف علامة تجارية +",
    editBrands: "تحرير العلامات التجارية",
    "brandName": "اسم العلامة التجارية",
    "edit": "تعديل",
    "delete": "حذف",
    "submit": "إرسال",
    brandList: "قائمة العلامات التجارية",
    searchBrandName: "البحث حسب اسم العلامة التجارية"
  },
  UnitDetails: {
    "search": "البحث حسب اسم الوحدة",
    "unit": "وحدة",
    "addUnit": "أضف وحدة +",
    "editUnit": "تحرير الوحدة",
    "unitPlaceholder": "أدخل اسم الوحدة",
    "unitName": "إسم الوحدة",
    "submit": "إرسال",
    "edit": "تعديل",
    "delete": "حذف",
    "isMeasurable": "بائس",
    unitList: "قائمة الوحدات"
  },
  AllProduct: {
    product: "المنتجات",
    showExpireBefore: "حدد تاريخ انتهاء الصلاحية",
    searchProducts: "البحث حسب اسم المنتج",
    uploadBulk: "تحميل مجمّع",
    addNewProduct: "إضافة منتج جديد",
    InventoryManage: "إدارة المخزون",
    productId: "رقم المنتج",
    sellingPrice: "سعر البيع",
    expiryDate: "تاريخ الانتهاء",
    Expire: "تنقضي",
    status: "الحالة",
    action: "الإجراء",
    availableQuantity: "الكمية المتوفرة",
    fileUpload: "تحميل الملف",
    lineOne: "الرجاء النقر فوق زر التنزيل وتنزيل ملف Excel",
    lineTwo: "ثم قم بتحرير ملف Excel وتحديث منتجات متجرك",
    lineThree: "السعر وتحميله مرة أخرى",
    lineFour: "بعد اكتمال التحميل ، انتقل إلى نقطة البيع الخاصة بك وانقر فوق",
    lineFive: "انتقل إلى لوحة تحكم المنتج / المزامنة",
    lineSix: "قم بتحميل تنسيق ملف xml أو xlsm فقط",
    clickToDownload: "اضغط للتحميل",
    upload: "رفع",
    edit: "تعديل",
    delete: "حذف",
    allProducts: "جميع المنتجات",
    Back: "خلف",
    quantity: "كمية",
    valid: "صالح",
    expired: "منتهي الصلاحية",
    Instock: "في الأوراق المالية",
    outofstock: "إنتهى من المخزن",
    selectcategory: "اختر الفئة",
    Yes: "نعم",
    No: "لا",
    addQuantity: "إضافة الكمية",
    add: "يضيف",
    addInventory: "إضافة المخزون",
    purchasePrice: "سعر الشراء",
    enterPurchasePrice: "أدخل سعر الشراء",
    purchaseDate: "تاريخ الشراء",
    notes: "ملاحظات",
    enterNotes: "أدخل الملاحظات",
    update: "تحديث",


  },


  AddNewProduct: {
    productCreation: "ابتكار المنتج",
    productEdit: "تحرير المنتج",
    productInformation: "معلومات المنتج",
    uploadImage: "تحميل صورة",
    preview: "معاينة",
    setDefault: "تعيين كافتراضي",
    notAllowedBeforeUpload: "غير مسموح به قبل التحميل",
    productName: "إسم المنتج",
    enterValidName: "إدخال إسماً صحيحاً",
    unit: "وحدة المنتج",
    enterValidUnit: "إدخال وحدة صحيحة",
    addUnit: "إضافة وحدة",
    sellingPrice: "سعر البيع",
    productSellingPrice: "إدخال سعر البيع",
    productDescription: "وصف المنتج",
    pleaseEnterProductDescription: "يرجى إدخال وصف المنتج",
    minimumThreeRows: "3 صفوف على الأقل",
    purchasingPrice: "سعر الشراء",
    mrp: "سعر التجزئة المقترح",
    category: "الفئة",
    selectCategory: "حدد الفئة",
    addCategory: "إضافة فئة",
    brand: "العلامة التجارية",
    selectBrand: "حدد العلامة التجارية",
    addBrand: "إضافة علامة تجارية",
    barcode: "الباركود",
    inventoryManage: "إدارة المخزون",
    quantity: "الكمية",
    expiryDate: "تاريخ الانتهاء",
    applyTax: "تطبيق الضريبة",
    selectTax: "حدد الضريبة",
    addTax: "إضافة ضريبة",
    taxInclude: "تضمين الضريبة",
    applyDiscount: "تطبيق الخصم",
    addDiscount: "إضافة خصم",
    selectDiscount: "حدد الخصم",
    updateProduct: "تحديث المنتج",
    addProduct: "إضافة المنتج",
    moreOption: "المزيد من الخيارات",
    "hideOption": "إخفاء الخيار",
    productUnit: "وحدة المنتج",
    selectUnit: "حدد الوحدة",
    purchasingPriceOfProduct: "سعر شراء المنتج",
    productMRP: "المنتج MRP",
    productBarcode: "الباركود المنتج",
    stockLevelAlert: "تنبيه مستوى المخزون",
    submit: "إرسال",
    edit: "تعديل",
    delete: "حذف",
    update: "تحديث",
    Back: "خلف",
    editInventory: "تحرير المخزون"

  },
  Billing: {
    selectSalesExecutive: "تحديد المبيعات التنفيذية",
    searchProducts: "البحث عن المنتجات...",
    searchSalesExecutive: "ابحث عن مدير مبيعات...",
    searchCustomer: "بحث عن زبون ...",
    select: "تحديد",
    expiredProduct: "المنتج منتهي الصلاحية",
    productExpiring: "منتج منتهي الصلاحية",
    applyDiscount: "تطبيق الخصم",
    productExpiryClickHere: "انقر هنا لتاريخ انتهاء الصلاحية",
    productName: "اسم المنتج",
    mrp: "سعر البيع بالتجزئة",
    sellingPrice: "سعر البيع",
    price: "السعر",
    quantity: "الكمية",
    remove: "إزالة",
    emptyCart: "إفراغ السلة",
    customer: "العميل",
    change: "تغيير",
    salesExecutive: "المبيعات التنفيذية",
    tax: "ضريبة",
    discount: "الخصم",
    applyAdditionalDiscount: "تطبيق خصم إضافي",
    flateDiscount: "خصم مسطح",
    total: "المجموع",
    fastPay: "دفع سريع",
    selectCustomer: "تحديد العميل",
    selectDiscount: "حدد الخصم",
    selectPaymentMode: "حدد وضع الدفع",
    putOnHold: "ضعه على الانتظار",
    submit: "إرسال",
    clearCart: "مسح السلة",
    paymentSuccess: "الدفع الناجح!",
    customerName: "اسم الزبون",
    orderId: "رقم التعريف الخاص بالطلب",
    totalAmount: "المبلغ الإجمالي",
    paymentType: "نوع الدفع",
    salesExecutiveName: "اسم مسؤول المبيعات",
    pullBack: "اسحب للخلف",
    save: "يحفظ",
    sendToKOT: "أرسل إلى كوت",
    item: "غرض",
    table: "طاولة",
    removeTable: "إزالة طاولة",
    products: "منتجات",
    chooseCategory: "اختر الفئة"

  },
  FloorDetails: {
    search: "البحث حسب اسم الطابق",
    addFloor: "إضافة طابق +",
    editFloor: "تحرير الكلمة",
    name: "الاسم",
    location: "الموقع",
    tableCount: "عدد الطاولات",
    date: "التاريخ",
    edit: "تعديل",
    delete: "حذف",
    submit: "إرسال",
    namePlaceholder: "أدخل اسم الطابق",
    locationPlaceholder: "أدخل اسم الموقع",
    floorPlan: "خريطة الطابق",
    editFloorPlan: "تحرير خريطة الطابق",
    height: "ارتفاع",
    width: "عرض",
    noOfSeats: "عدد المقاعد:",
    floorList: "قائمة الطوابق"

  },
  TableDetails: {
    search: "البحث حسب اسم الجدول",
    addTable: "إضافة طاولة +",
    editTable: "تحرير الجدول",
    tableName: "اسم الطاولة",
    capacity: "سعة الطاولة",
    date: "التاريخ",
    edit: "تعديل",
    delete: "حذف",
    submit: "إرسال",
    selectFloor: "اختر الطابق",
    tableNamePlaceholder: "اسم الطاولة",
    capacityPlaceholder: "أدخل سعة الجلوس للطاولة",
    tableList: "قائمة الجدول"

  },
  StockDashboard: {
    poNumber: "رقم الطلب",
    status: "الحالة",
    updated: "تم التحديث",
    expectedOn: "التوقعات في",
    vendor: "المورد",
    destination: "الوجهة",
    amount: "المبلغ",
    actions: "الإجراءات",
    notes: "ملاحظات",
    productName: "اسم المنتج",
    purchasingPrice: "سعر الشراء",
    lastUpdated: "آخر تحديث",
    quantity: "الكمية",
    inventoryId: "معرف المخزون"
  },
  PurchaseOrderPage: {
    vendor: "المورد",
    vendorPlaceholder: "اختر المورد",
    shipTo: "الشحن إلى",
    shipToPlaceholder: "اختر",
    poNumber: "رقم الطلب",
    poInvoiceNumber: "رقم فاتورة الطلب",
    expectedDelivery: "التسليم المتوقع",
    billingDate: "تاريخ الفوترة",
    applyTaxAfterDiscount: "تطبيق الضريبة بعد الخصم",
    notes: "ملاحظات",
    addItem: "إضافة عنصر",
    srNo: "الرقم التسلسلي",
    productName: "اسم المنتج",
    unitBuyingPrice: "سعر الشراء للوحدة",
    unitBasePrice: "سعر الوحدة الأساسي",
    unitSellingPrice: "سعر البيع للوحدة",
    unitBasePriceWithoutTax: "سعر الوحدة الأساسي (بدون ضريبة)",
    unitBuyingPriceWithTax: "سعر الشراء للوحدة (مع الضريبة)",
    mrp: "السعر الإجمالي المقترح",
    quantity: "الكمية",
    discount: "الخصم",
    tax: "الضريبة",
    actions: "الإجراءات",
    calculateUnitBuyingPrice: "حساب سعر الشراء للوحدة",
    discountType: "نوع الخصم",
    discountValue: "قيمة الخصم",
    percentage: "نسبة",
    flat: "مستوى",
    namePlaceholder: "اختر المنتج",
    taxPlaceholder: "اختر الضرائب",
    discountPlaceholder: "اختر النوع",
    createItem: "إنشاء عنصر",
    submit: "إرسال",
    poNumberPlaceholder: 'أدخل رقم الطلب',
    poInvoicePlaceholder: 'أدخل رقم فاتورة الطلب'


  },
  AccountAndSettings: {
    posSetting: "إعدادات نقطة البيع",
    invoiceSettings: "إعدادات الفاتورة",
    invoiceSize: "حجم الفاتورة",
    preview: "معاينة",
    sizePlaceholder: "اختر حجم الفاتورة",
  },
  CategoryDetails: {
    "search": "االبحث حسب اسم الفئة",
    "addCategory": "+ إضافة فئة",
    "editCategory": "تحرير الفئة",
    "category": "فئة",
    "inputText": "اكتب هنا للفئة",
    "edit": "تعديل",
    "delete": "حذف",
    "submit": "إرسال",
    categoryList: "قائمة الفئات"
  },

  SalesExecutive: {
    search: "البحث حسب اسم مدير المبيعات",
    addSalesExecutive: "+ إضافة مدير مبيعات",
    salesExecutive: "المبيعات التنفيذي",
    activeInactive: "نشيط/غير نشط",
    active: "نشيط",
    inactive: "غير نشط",
    setOnDuty: "انطلق في الخدمة",
    addSalesExecutiveName: "إضافة اسم مسؤول المبيعات",
    editSalesExecutiveName: "تحرير اسم مسؤول المبيعات",
    salesExecutiveName: "اسم مسؤول المبيعات",
    enterSalesExecutiveName: "أدخل اسم مسؤول المبيعات",
    edit: "تعديل",
    delete: "حذف",
    submit: "إرسال",
    salesExcutiveList: "قائمة المبيعات التنفيذية"

  },
  StoreSetting: {
    storeDetails: "تفاصيل المتجر",
    storeName: "اسم المتجر",
    storeId: "معرف المتجر",
    currency: "العملة",
    gst: "ضريبة السلع والخدمات",
    deliveryDetails: "تفاصيل التسليم",
    homeDelivery: "توصيل للمنزل",
    minimumOrderLimit: "حد الطلب الأدنى",
    freeDeliveryWithin: "توصيل مجاني داخل",
    storeTiming: "مواعيد المتجر",
    storeOpeningTime: "وقت فتح المتجر",
    storeClosingTime: "وقت إغلاق المتجر",
    storeCloseDay: "يوم إغلاق المتجر",
    address: "العنوان",
    area: "المنطقة",
    city: "المدينة",
    pincode: "الرمز البريدي",
    latitude: "خط العرض",
    longitude: "خط الطول",
    contact: "اتصال",
    mobile: "الهاتف المحمول",
    emailId: "معرف البريد الإلكتروني",
    customerID: "معرف العميل",
    editStore: "تعديل المتجر",
    licenseDetails: "تفاصيل الترخيص",
    licenseKey: "مفتاح الترخيص",
    status: "الحالة",
    expiryDate: "تاريخ الانتهاء",
    remainigDate: "الأيام المتبقية"
  },
  StoreEdit: {
    storeInformation: "معلومات المتجر",
    search: "بحث...",
    storeId: "معرف المتجر",
    storeName: "اسم المتجر",
    currency: "العملة",
    gst: "ضريبة السلع والخدمات",
    deliveryDetails: "تفاصيل التوصيل",
    minimumOrderLimit: "الحد الأدنى للطلب",
    deliveryCharge: "رسوم التوصيل",
    freeDeliveryWithin: "توصيل مجاني داخل",
    storeTiming: "أوقات المتجر",
    storeOpeningTime: "وقت فتح المتجر",
    storeClosingTime: "وقت إغلاق المتجر",
    storeCloseDay: "يوم إغلاق المتجر",
    address: "العنوان",
    city: "المدينة",
    pincode: "الرمز البريدي",
    latitude: "خط العرض",
    longitude: "خط الطول",
    area: "المنطقة",
    changeAddress: "تغيير العنوان",
    updateStore: "تحديث المتجر",
    mapAddress: "نحتاج إلى عنوان متجرك لإعداد متجرك عبر الإنترنت",
    next: "التالي",
    back: "خلف",
    homeDeliveryAvailable: "التسليم متاح",
    cancel: "يلغي"

  },
  addStore: {
    "AddStore": "إضافة متجر",
    "AddressConfirmation": "تأكيد العنوان",
    "ShopNo": "رقم المتجر، رقم الممر، رقم المبنى وغيرها",
    // "Selectedaddressonmap": "العنوان المحدد على الخريطة",
    "Selectedaddressonmap": "العنوان",
    "State": "الولاية",
    "Pincode": "الرمز البريدي",
    "Country": "البلد",
    "USETHISADDRESS": "استخدم هذا العنوان",
    "StoreSummary": "ملخص المتجر",
    "StoreName": "اسم المتجر",
    "StoreCategory": "فئة المتجر",
    "StoreCurrency": "عملة المتجر",
    "StoreAddress": "عنوان المتجر",
    "CREATESTORE": "إنشاء متجر",
    "City": "المدينة",
    "EnterStoreName": "أدخل اسم المتجر",
    "SelectCountry": "اختر الدولة",
    "SelectStoreType": "اختر نوع المتجر",
    "ChooseAddressUsingMap": "اختر العنوان باستخدام الخريطة",
    "NEXT": "التالي",
    "Back": "خلف",
    "Mobile": "متحرك",
    "mobileplaceholder": "الرجاء إدخال رقم الهاتف المحمول",
    "StoreNotes": "نحتاج إلى بعض التفاصيل من جانبك حتى تتمكن من البدء في استخدام هذا التطبيق المذهل.",
    "WelcomeNotes": "مرحبًا بك في Ezy POS",
  },
  Report: {
    selectCustomDate: "حدد تاريخًا مخصصًا",
    search: "بحث...",
    selectMonth: "حدد شهرًا",
    getReport: "احصل على التقرير",
    date: "تاريخ",
    total: "الإجمالي",
    details: "التفاصيل",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    emptyPageNote: "يرجى تحديد التاريخ أو الشهر للحصول على التقرير",
    showChart: "إظهار الرسم البياني",
    reportTransactionChart: "تقرير مخطط المعاملة",
    customer: "العميل",
    paymentMode: "طريقة الدفع",
    paymentId: "معرف الدفع",
    viewOrder: "عرض الطلب",
    products: "المنتجات",
    quantity: "الكمية",
    discount: "الخصم",
    tax: "ضريبة",
    transactionsReportDetails: "تفاصيل تقرير المعاملات"

  },

  Transaction: {
    "transactionPleaseSelectDate": "المعاملة يرجى تحديد التاريخ",
    "search": "بحث المعاملات",
    "selectCustomDate": "حدد تاريخًا مخصصًا",
    "paymentType": "نوع الدفع",
    "servedBy": "قدم بواسطة",
    "paymentId": "معرف الدفع",
    "customer": "عميل",
    "date": "تاريخ",
    "total": "الإجمالي",
    "endDate": "تاريخ الانتهاء",
    "startDate": "تاريخ البدء",
    "find": "يجد",
    "today": "اليوم",
    "last7Days": "اخر 7 ايام",
    "last30Days": "اخر 30 ايام",
    "last3Month": "آخر 3 أشهر",
    "last6Month": "آخر 6 أشهر",
    "transactionInLast": "الصفقة في الماضي",
    "transactionDetails": "تفاصيل الصفقه",
    "selectMonth": "اختر الشهر",
    "transaction": "عملية",
    transactionList: "قائمة المعاملات",
    selectSalesExecutive: "حدد مدير المبيعات"


  },

  SingleTransaction: {
    "products": "المنتجات",
    "quantity": "الكمية",
    "total": "الإجمالي",
    "tax": "ضريبة",
    "discount": "الخصم"
  },

  trailNotification: {
    ThereAre: "يوجد",
    leftOnYourTrail: "متبقي على دربك.",
    clickHereToUpgrade: "انقر هنا للترقية",
    UpgradeToUnlockThisFeature: "الترقية لفتح هذه الميزة",
    Upgrade: "الترقية",
    day: "يوم",
    days: "أيام",
    freeTrialPlan: "خطة تجريبية مجانية"

  }









};

export default translation;
