const translation = {
  Dashboard: {
    overview: "Overview",
    cardOneHeading: "share Store Link",
    cardOneDescription:
      "Customers can visit the following link and place their orders.",
    cardOneShareVia: "Share Via",
    cardTwoHeading: "TOTAL SALES",
    cardTwoPrice: "{{totalPrice}}",
    cardThreeHeading: "STORE VIEWS",
    cardThreeNumber: "{{totalStoreView}}",
    monthTransactions: "Month Transactions",
    topSellinghProducts: "Top Selling Product",
    customerOfTheMonth: "Customer Of The Month",
  },
  SideNav: {
    dashboard: "Dashboard",
    tableManagement: "Table Manage",
    billing: "Billing",
    tables: "Tables",
    transaction: "Transaction",
    onlineOrder: "Online Order",
    product: "Product",
    productsManagement: "Products Management",
    discountsOffers: "Discounts/Offers",
    discount: "Discount",
    taxes: "Taxes",
    customers: "Customers",
    customersDetails: "Customers Details",
    brands: "Brands",
    brandsDetails: "Brands Details",
    units: "Units",
    unitsDetails: "Units Details",
    category: "Category",
    categoryDetails: "Category Details",
    salesExecutive: "Sales Executive",
    salesExecutiveDetails: "Sales Executive Details",
    storeSetting: "Store Setting",
    restaurantManagement: "Restaurant Management",
    floor: "Floor",
    table: "Table",
    inventoryManagement: "Inventory Management",
    stockDashboard: "Inventory Dashboard",
    purchaseOrder: "Purchase Order",
    accountSettings: "Account/Settings",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    arabic: "عربي",
    marathi: "मराठी",
    hindi: "हिंदी",
    report: "Report",
    logout: "Logout",
  },

  TopHeader: {
    allOnlineOrders: "All Online Orders",
    orderDetails: "Order Details",
    allProducts: "All Products",
    productDetails: "Product Details",
    addNewProduct: "Add New Product",
    customerDetails: "Customer Details",
    discountDetails: "Discount Details",
    taxesDetails: "Tax Details",
    brandsDetails: "Brand Details",
    unitsDetails: "Unit Details",
    categoryDetails: "Category Details",
    salesExecutive: "Sales Executive",
    loginPage: "Login Page",
    storeSetting: "Store Setting",
    storeEdit: "Edit Store",
    billing: "Billing",
    "reportDetails": "Report Details",


  },

  Tables: {
    selectTable: "Select Table",
    selectPlaceholderTable: "Select Table",
    table: "Table",
    occupied: "Occupied",
    newOrder: "New Order",
    orderDetails: "Order Details",
    edit: "Edit",
    split: "Split",
    merge: "Merge",
    move: "Move",
    orderNo: "Order No",
    status: "Status",
    pending: "Pending",
    category: "Category",
    dateAndTime: "Date and Time",
    kotHistory: "KOT History",
    srNo: "Sr.No",
    itemName: "Item Name",
    quantity: "Quantity",
    subtotal: "Subtotal",
    tax: "Tax",
    charges: "Charges",
    item: "Item",
    total: "Total",
    print: "Print",
    cancel: "Cancel",
    complete: "Complete",
    selectWaiter: "Select Waiter",
    back: "Back",
    confirm: "Confirm",
    waiter: "Waiter",
    totalAmount: "Total Amount",
    waiterName: "Waiter Name",
    date: "Date",
    time: "Time",
    shareReceipt: "Share Receipt",
    backToTable: "Back To Table",
    receiptPreview: "Receipt Preview",
    discount: "Discount",
    add: "Add",
    balance: "Balance",
    selectPaymentMethod: "Select Payment Method",
    addPaymentMethod: "Add Payment Method",
    paymentOptions: "Payment Options"



  },
  allOnlineOrder: {
    Pending: "Pending",
    Accepted: "Accepted",
    InProgress: "In-Progress",
    Dispatch: "Dispatch",
    Delivered: "Delivered",
    Cancelled: "Cancelled",
    CustomerName: "Search customer name",
    SelectStatus: "Select Status",
    Back: "Back",
    OrderId: "Order Id",
    Date: "Date",
    Customer: "Customer",
    Status: "Status",
    Amount: "Amount",
    RejectOrder: "Reject Order",
    OrderID: "Order ID ",
    OrderStatus: " Order Status ",
    OrderBookingTime: "Order Booking Time ",
    Item: "Item",
    Discount: "Discount ",
    ItemPrice: "Item Price ",
    Notes: "Notes",
    Addordernoteshere: "Add order notes here",
    ADD: "ADD",
    ItemTotal: "Item Total",
    Delivery: "Delivery",
    GrandTotal: "Grand Total",
    Customerdetails: "Customer details",
    Name: "Name:",
    Mobile: "Mobile:",
    Address: "Address:",
    City: "City:",
    State: "State:",
    Postcode: "Postcode:",
    Payment: "Payment:",
    CurrentStatus: "Current Status",
    noteOne: "You don't have any",
    noteTwo: "Share your store's link with your customers on social media to get more orders.",
    free: "Free",
    onlineOrders: "Online Orders"
  },

  CustomerDetails: {
    search: "Search by customer name",
    addCustomers: "+ Add customers",
    editCustomer: "Edit Customer Details",
    customersName: "Customer Name",
    email: "Email",
    contactNo: "Contact No",
    address: "Address",
    city: "City",
    state: "State",
    country: "Country",
    addCustomer: "Add Customer",
    name: "Name",
    emailAddress: "Email address",
    mobileNumber: "Mobile Number",
    submit: "Submit",
    enterCustomerName: "Enter customer name",
    enterCustomerEmail: "Enter customer email",
    enterMobileNumber: "Enter mobile number",
    enterAddress: "Enter address",
    enterCity: "Enter city",
    enterState: "Enter State",
    enterCountry: " Enter country",
    edit: "Edit",
    delete: "Delete",
    customersList: "Customers List",
    totalCustomerCount: "Total Customer Count",
    newCustomerCount: "New Customer Count",
    customerOftheMonth: "Customer Of the Month"
  },

  DiscountDetails: {
    search: "Search...",
    createCoupon: "Create Coupon",
    discount: "Discount Name",
    SearchDiscountName: "Search by discount name",
    startDate: "Start Date",
    endDate: "End Date",
    Expire: "Expire",
    removeDiscount: "Remove discount",
    applyDiscount: "Apply discount",
    edit: "Edit",
    delete: "Delete",
    addDiscount: "Add Discount",
    editDiscount: "Edit Discount",
    discountName: "Discount Name",
    discountValue: "Discount Value",
    enterDiscountName: "Enter discount name",
    enterDiscountValue: "Enter discount value",
    productName: "Product Name",
    beforeDiscount: "Before discount",
    afterDiscount: "After discount",
    removeDiscountFromProduct: "Remove from product",
    applyDiscountOnProduct: "Apply on product",
    submit: "Submit",
    discountTableHeading: "Discount List",
    SearchProductByName: "Search product by name",
    selectedDiscount: "Selected Discount",
    selectCategory: "Select Category",
    RemoveMappedDiscount: "Remove Mapped Discount"



  },

  TaxDetails: {
    search: "Search tax",
    tax: "tax",
    taxes: "Tax name",
    values: "Tax value",
    removeTax: "Remove tax",
    applyTax: "Apply tax",
    edit: "Edit",
    delete: "Delete",
    removeTaxFromProduct: "Remove tax from product",
    applyTaxOnProduct: "Apply tax on product",
    addTax: "Add Tax +",
    editTax: "Edit Tax",
    taxName: "Enter tax name",
    taxValueInPercent: "Tax Value in %",
    enterTaxValue: "Enter tax value",
    submit: "Submit",
    remove: "Remove",
    productName: "Product Name",
    beforeTax: "BeforeTax",
    afterTax: "AfterTax",
    apply: "Apply",
    taxTableHeading: "Taxes List",
    selectedTax: "Selected Tax ",
    removeMappedTax: "Remove Mapped Tax",
    searchTaxName: "Search by tax name"
  },

  BrandDetails: {
    "search": "Search brand",
    "brand": "Brand Name",
    "addBrands": "Add Brand +",
    editBrands: "Edit Brand",
    "brandName": "Brand Name",
    brandPlaceholder: "Enter brand name",
    edit: "Edit",
    delete: "Delete",
    "submit": "Submit",
    brandList: "Brands List",
    searchBrandName: "Search by brand name"
  },

  UnitDetails: {
    "search": "Search by unit name",
    "unit": "Unit",
    "addUnit": "Add Unit +",
    "editUnit": "Edit Unit",
    "unitName": "Unit Name",
    "unitPlaceholder": "Enter unit name",
    "isMeasurable": "Measurable",
    edit: "Edit",
    delete: "Delete",
    "submit": "Submit",
    unitList: "Units List",

  },

  AllProduct: {
    product: "Product Name",
    showExpireBefore: "Set Expire Date",
    searchProducts: "Search by product name",
    uploadBulk: "Upload Bulk",
    addNewProduct: "Add new product",
    productId: "Product Id",
    sellingPrice: "Selling Price",
    expiryDate: "Expiry Date",
    Expire: "Expire",
    InventoryManage: "Inventory Manage",
    status: "Status",
    action: "Action",
    availableQuantity: "Available quantity",
    fileUpload: "File Upload",
    lineOne: "Please click on the download button and download the Excel file,",
    lineTwo: "Then edit excel file and update your store products",
    lineThree: "price and upload it again.",
    lineFour: "After the upload is complete, go to the product dashboard",
    lineFive: "App and Backup/Sync button.",
    lineSix: "Only upload xml or xlsm file format",
    clickToDownload: "Click to download",
    upload: "Upload",
    edit: "Edit",
    delete: "Delete",
    allProducts: "All Products",
    Back: "Back",
    quantity: "Quantity",
    valid: "Valid",
    expired: "Expired",
    Instock: "In stock",
    outofstock: "out of stock",
    selectcategory: "Select Category",
    Yes: "Yes",
    No: "No",
    addQuantity: "Enter Quantity",
    add: "Add",
    addInventory: "Add Inventory",
    purchasePrice: "Purchase Price",
    enterPurchasePrice: " Enter Purchase Price",
    purchaseDate: "Purchase Date",
    notes: "Notes",
    enterNotes: "Enter notes",
    update: "Update",


  },

  AddNewProduct: {
    productInformation: "ProductInformation",
    productCreation: "Product Creation",
    productEdit: "Product Edit",
    uploadImage: "Upload Image",
    preview: "Preview",
    setDefault: "Set Default",
    notAllowedBeforeUpload: "Not allowed before upload",
    productName: "Product Name",
    enterValidName: "Enter valid name",
    unit: "Unit",
    enterValidUnit: "Enter valid unit",
    addUnit: "Add Unit",
    sellingPrice: "Selling Price",
    productSellingPrice: "Product selling price",
    productDescription: "Product Description",
    minimumThreeRows: "Minimum 3 rows",
    pleaseEnterProductDescription: "Please enter product description",
    purchasingPrice: "Purchasing Price",
    mrp: "MRP",
    category: "Category",
    selectCategory: "Select Category",
    addCategory: "Add Category",
    brand: "Brand",
    selectBrand: "Select Brand",
    addBrand: "Add Brand",
    barcode: "Barcode",
    inventoryManage: "Inventory Manage",
    quantity: "Quantity",
    expiryDate: "Expiry Date",
    applyTax: "Apply Tax",
    selectTax: "Select Tax",
    addTax: "Add Tax",
    taxInclude: "Tax Include",
    applyDiscount: "Apply Discount",
    addDiscount: "Add Discount",
    selectDiscount: "Select Discount",
    moreOption: "More option",
    hideOption: "Hide option",
    updateProduct: "Update Product",
    addProduct: "Add Product",
    productUnit: "ProductUnit",
    selectUnit: "Select Unit",
    purchasingPriceOfProduct: "Purchasing price of product",
    productMRP: "Product MRP",
    productBarcode: "Product barcode",
    stockLevelAlert: "Stock Level Alert",
    edit: "Edit",
    delete: "Delete",
    submit: "Submit",
    update: "Update",
    Back: "Back",
    editInventory: "Update Inventory"
  },

  Billing: {
    selectSalesExecutive: "Select Sales Executive",
    searchProducts: "Search Products...",
    searchCustomer: "Search Customer...",
    searchSalesExecutive: "Search Sales Executive",
    select: "Select",
    expiredProduct: "Expired Product",
    productExpiring: "Product Expiring",
    applyDiscount: "Apply Discount",
    productExpiryClickHere: "Product Expiry Click here",
    productName: "Product Name",
    mrp: "MRP",
    sellingPrice: "Selling Price",
    price: "Price",
    quantity: "Quantity",
    remove: "Remove",
    emptyCart: "Empty Cart",
    customer: "Customer",
    change: "change",
    salesExecutive: "Sales Executive",
    tax: "Tax",
    discount: "Discount",
    applyAdditionalDiscount: "Apply additional discount",
    flateDiscount: "Flate discount",
    total: "Total",
    fastPay: "FastPay",
    selectCustomer: "Select Customer",
    selectDiscount: "Select Discount",
    afterDiscount: "After Discount",
    selectPaymentMode: "Select payment mode",
    putOnHold: "Put on hold",
    submit: "Submit",
    clearCart: "Clear Cart",
    paymentSuccess: "Payment Success!",
    customerName: "Customer Name",
    orderId: "Order Id",
    totalAmount: "Total Amount",
    paymentType: "Payment type",
    salesExecutiveName: "Sales Executive Name",
    pullBack: "PullBack",
    save: "Save",
    sendToKOT: "Send To KOT",
    item: "Item",
    table: "Table",
    removeTable: "Remove Table",
    products: "Products",
    chooseCategory: "Choose Category"
  },


  FloorDetails: {
    search: "Search by floor name",
    addFloor: "Add Floor +",
    editFloor: "Edit Floor",
    name: "Name",
    location: "Location",
    tableCount: "Table Count",
    date: "Date",
    edit: "Edit",
    delete: "Delete",
    submit: "Submit",
    namePlaceholder: "Enter floor name",
    locationPlaceholder: "Enter location name",
    floorPlan: "Floor Plan",
    editFloorPlan: "Edit Floor Plan",
    height: "Height",
    width: "Width",
    noOfSeats: "No. of Seats:",
    floorList: "Floor List",

  },
  TableDetails: {
    search: "Search by table name",
    addTable: "Add Table +",
    editTable: "Edit Table",
    tableName: "Table name",
    capacity: "Table capacity",
    date: "Date",
    edit: "Edit",
    delete: "Delete",
    submit: "Submit",
    selectFloor: "Select floor",
    tableNamePlaceholder: "table name",
    capacityPlaceholder: " Enter table Seating Capacity",
    tableList: "Table List"
  },
  StockDashboard: {
    poNumber: "PO number",
    status: "Status",
    updated: "Updated",
    expectedOn: "Expected on",
    vendor: "Vendor",
    destination: "Destination",
    amount: "Amount",
    actions: "Actions",
    notes: "Notes",
    productName: "Product Name",
    purchasingPrice: "	Purchasing Price",
    lastUpdated: 'Last Updated',
    quantity: "Quantity",
    inventoryId: "Inventory Id"

  },

  PurchaseOrderPage: {
    vendor: "Vendor",
    vendorPlaceholder: "Select vendor",
    shipTo: "Ship To",
    shipToPlaceholder: "Select ",
    poNumber: "PO number",
    poInvoiceNumber: "PO Invoice Number",
    expectedDelivery: "Expected Delivery",
    billingDate: "Billing date",
    applyTaxAfterDiscount: "Apply Tax After Discount",
    notes: "Notes",
    addItem: " Add Item",
    srNo: "Sr No",
    productName: "Product Name",
    unitBuyingPrice: "unit Buying Price",
    unitBasePrice: "unit Base Price",
    unitSellingPrice: "unit Selling Price",
    unitBasePriceWithoutTax: "Unit Base Price (Without Tax)",
    unitBuyingPriceWithTax: "Unit Buying Price (With Tax)",
    mrp: "MRP",
    quantity: "Quantity",
    discount: "Discount",
    tax: "Tax",
    actions: "Actions",
    calculateUnitBuyingPrice: "Calculate Unit buying Price",
    discountType: "DiscountType",
    discountValue: "DiscountValue",
    percentage: "Percentage",
    flat: "Flat",
    namePlaceholder: "Select Product",
    taxPlaceholder: "Select taxes",
    discountPlaceholder: "Select type",
    createItem: "Create Item",
    submit: "Submit",
    poNumberPlaceholder: 'Enter Po number',
    poInvoicePlaceholder: 'Enter Po invoice number'


  },
  AccountAndSettings: {
    posSetting: "Pos Setting",
    invoiceSettings: "Invoice Settings",
    invoiceSize: "Invoice Size",
    preview: " Preview",
    sizePlaceholder: "Select invoice size"

  },
  CategoryDetails: {
    "search": "Search by category name",
    "addCategory": "+ Add Category",
    "editCategory": "Edit Category",
    "category": "Category Name",
    "inputText": "Enter category name",
    edit: "Edit",
    delete: "Delete",
    "submit": "Submit",
    categoryList: "Category List"
  },

  SalesExecutive: {
    search: "Search by Sales Executive name",
    addSalesExecutive: "+ Add Sales Executive",
    salesExecutive: "Sales Executive Name",
    activeInactive: "Active/Inactive",
    active: "Active",
    inactive: "Inactive",
    setOnDuty: "Set on duty",
    addSalesExecutiveName: "Add Sales Executive Name",
    editSalesExecutiveName: "Edit Sales Executive Name",
    salesExecutiveName: "Sales Executive Name",
    enterSalesExecutiveName: "Enter sales executive name",
    edit: "Edit",
    delete: "Delete",
    submit: "Submit",
    salesExcutiveList: "SalesExcutive List"

  },

  StoreSetting: {
    storeDetails: "STORE DETAILS",
    storeName: "Store Name",
    storeId: "Store Id",
    currency: "Currency",
    gst: "GST",
    deliveryDetails: "DELIVERY DETAILS",
    homeDelivery: "Home Delivery",
    minimumOrderLimit: "Minimum order limit",
    freeDeliveryWithin: " Free delivery within",
    storeTiming: "STORE TIMING",
    storeOpeningTime: "Store opening time",
    storeClosingTime: "Store closing time",
    storeCloseDay: "Store close day",
    address: "ADDRESS",
    area: "Area",
    city: "City",
    pincode: "Pincode",
    latitude: "Latitude",
    longitude: "Longitude",
    contact: "CONTACT",
    mobile: "Mobile",
    emailId: "Email Id",
    customerID: "Customer ID",
    editStore: "EDIT STORE",
    licenseDetails: "LICENSE DETAILS",
    licenseKey: "License Key",
    status: "Status",
    expiryDate: "Expiry Date",
    remainigDate: "Remainig Date"
  },

  StoreEdit: {
    storeInformation: "Store Information",
    storeId: "Store Id",
    storeName: "Store name",
    currency: "Currency",
    gst: "GST",
    deliveryDetails: "Delivery details",
    minimumOrderLimit: "Minimum order limit",
    deliveryCharge: "Delivery charge",
    freeDeliveryWithin: "Free delivery within",
    storeTiming: "Store timing",
    storeOpeningTime: "Store opening time",
    storeClosingTime: "Store closing time",
    storeCloseDay: "Store close day",
    address: "Address",
    city: "City",
    pincode: "Pincode",
    latitude: "Latitude",
    longitude: "Longitude",
    area: "Area",
    changeAddress: "Change address",
    updateStore: "Update Store",
    mapAddress: "We need your store address to set up your shop online",
    next: "NEXT",
    back: "Back",
    homeDeliveryAvailable: "Home delivery available",
    cancel: "Cancel"

  },
  addStore: {
    "AddStore": "Add Store",
    "AddressConfirmation": "Address Confirmation",
    "ShopNo": "Shop No, Lane No, Building No etc.",
    // "Selectedaddressonmap": "Selected address on map",
    "Selectedaddressonmap": " Address",
    "State": "State",
    "Pincode": "Pincode",
    "Country": "Country",
    "USETHISADDRESS": "USE THIS ADDRESS",
    "StoreSummary": "Store Summary",
    "StoreName": "Store name",
    "StoreCategory": "Store category",
    "StoreCurrency": "Store currency",
    "StoreAddress": "Store Address",
    "CREATESTORE": "CREATE STORE",
    "City": "City",
    "EnterStoreName": "Enter store name",
    "SelectCountry": "Select country",
    "SelectStoreType": "Select store type",
    "ChooseAddressUsingMap": "Add address using map",
    "NEXT": "NEXT",
    "Back": "BACK",
    "Mobile": "Mobile",
    "mobileplaceholder": "Please enter mobile number",
    "WelcomeNotes": "Welcome to Ezy POS",
    "StoreNotes": "We need a few details from your side so that you can get started with this amazing app."
  },

  Report: {
    selectCustomDate: "Select Custom Date",
    search: "Search...",
    selectMonth: "Select  Month",
    getReport: "Get Report",
    date: "Date",
    total: "Total",
    details: "Details",
    startDate: "Start Date",
    endDate: "End Date",
    emptyPageNote: "Report Please Select Date or Month",
    showChart: "Show Chart",
    reportTransactionChart: "Report Transaction Chart",
    customer: "Customer",
    paymentMode: "Payment Mode",
    paymentId: "Payment Id",
    viewOrder: "View Order",
    products: "Products",
    quantity: "Quantity",
    discount: "Discount",
    tax: "Tax",
    transactionsReportDetails: "Transactions Report Details"


  },

  Transaction: {
    transactionPleaseSelectDate: "Transaction PleaseSelect Date",
    search: "Search transactions",
    selectCustomDate: "Select Custom Date",
    paymentType: "Payment Type",
    servedBy: "Served By",
    paymentId: "Payment Id",
    customer: "Customer",
    date: "Date",
    total: "Total",
    endDate: "End Date ",
    startDate: "Start Date",
    find: "find",
    today: "Today",
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days",
    last3Month: "Last 3 Month",
    last6Month: "Last 6 Month",
    transactionInLast: "Transaction in last",
    transactionDetails: "Transaction Details",
    selectMonth: "Select Month",
    transaction: "Transaction",
    transactionList: "Transaction List",
    selectSalesExecutive: "Select SalesExecutive"


  },

  SingleTransaction: {
    "products": "Products",
    "quantity": "Quantity",
    "total": "Total",
    "tax": "tax",
    "discount": "Discount"
  },

  trailNotification: {
    ThereAre: " There are",
    leftOnYourTrail: "left on your trail.",
    clickHereToUpgrade: " Click here to Upgrade",
    UpgradeToUnlockThisFeature: "Upgrade to unlock this feature",
    Upgrade: "Upgrade",
    day: "day",
    days: "days",
    freeTrialPlan: "Free Trial Plan"

  }




};

export default translation;

