import { singleTransaction } from "../../../Redux/Transaction/TransactionSlice";

const translation = {
    Dashboard: {
        overview: "अवलोकन",
        cardOneHeading: "स्टोर लिंक शेअर करा",
        cardOneDescription: "ग्राहकें खालील लिंक पहावें आणि त्यांचे ऑर्डर तयार करू शकतात.",
        cardOneShareVia: "व्हिया शेअर",
        cardTwoHeading: "एकूण विक्री",
        cardTwoPrice: "{{totalPrice}}",
        cardThreeHeading: "स्टोर पहाणे",
        cardThreeNumber: "{{totalStoreView}}",
        monthTransactions: "महिन्याचे व्यवहार",
        topSellinghProducts: "सर्वाधिक विक्री होणारे उत्पादन",
        customerOfTheMonth: "महिन्याचे ग्राहक"
    },
    SideNav: {
        dashboard: "डॅशबोर्ड",
        tableManagement: "टेबल व्यवस्थापन",
        billing: "बिलिंग",
        tables: "टेबल",
        transaction: "व्यवहार",
        onlineOrder: "ऑनलाईन आदेश",
        product: "उत्पाद",
        productsManagement: "उत्पादने व्यवस्थापन",
        discountsOffers: "छूटे/ऑफर्स",
        discount: "छूट",
        taxes: "कर",
        customers: "ग्राहके",
        customersDetails: "ग्राहक तपशील",
        brands: "ब्रांड्स",
        brandsDetails: "ब्रांड तपशील",
        units: "युनिट्स",
        unitsDetails: "युनिट तपशील",
        category: "वर्ग",
        categoryDetails: "वर्ग तपशील",
        salesExecutive: "विक्री कार्यकारी",
        salesExecutiveDetails: "विक्री कार्यकारी तपशील",
        storeSetting: "स्टोर सेटिंग",
        restaurantManagement: "रेस्तरां प्रबंधन",
        floor: "ज़मीन",
        table: "मेज़",
        inventoryManagement: "सूची प्रबंधन",
        stockDashboard: "स्टॉकडैशबोर्ड",
        purchaseOrder: "क्रय आदेश",
        accountSettings: "खाता/सेटिंग्स",
        language: "भाष",
        selectLanguage: "भाषा निवडा",
        english: "English",
        arabic: "عربي",
        marathi: "मराठी",
        hindi: "हिंदी",
        "report": "अहवाल",
        "logout": "लॉग आउ"

    },
    TopHeader: {
        allOnlineOrders: "ऑनलाइन ऑर्डर सर्व",
        orderDetail: "ऑर्डर तपशील",
        allProducts: "सर्व उत्पादने",
        productDetails: "उत्पादन तपशील",
        addNewProduct: "नवीन उत्पादन जोडा",
        customerDetails: "ग्राहक तपशील",
        discountDetails: "छूट तपशील",
        taxesDetails: "कर तपशील",
        brandsDetails: "ब्रांड तपशील",
        unitsDetails: "एकक तपशील",
        categoryDetails: "वर्ग तपशील",
        salesExecutive: "विपणी कार्यकर्ता",
        loginPage: "लॉगिन पृष्ठ",
        storeSetting: "स्टोर सेटिंग",
        storeEdit: "स्टोर संपादित करा",
        billing: "बिलिंग",
        "reportDetails": "अहवाल तपशील"
    },
    Tables: {
        selectTable: "मेज़ निवडा",
        selectPlaceholderTable: "मेज़ निवडा",
        table: "मेज़",
        occupied: "आकारीत",
        newOrder: "नवीन ऑर्डर",
        orderDetails: "ऑर्डर तपशील",
        edit: "संपादित करा",
        split: "विभाजन",
        merge: "मर्ज",
        move: "हलवा",
        orderNo: "ऑर्डर क्रमांक",
        status: "स्थिती",
        pending: "प्रलंबित",
        category: "वर्ग",
        dateAndTime: "तारीख आणि वेळ",
        kotHistory: "KOT इतिहास",
        srNo: "क्रमांक",
        itemName: "आयटमचं नाव",
        quantity: "मात्रा",
        subtotal: "उपयोग",
        tax: "कर",
        charges: "शुल्क",
        item: "आयटम",
        total: "एकूण",
        print: "प्रिंट",
        cancel: "रद्द करा",
        complete: "पूर्ण",
        selectWaiter: "वेटर निवडा",
        back: "परत",
        confirm: "पुष्टी",
        waiter: "वेटर",
        totalAmount: "एकूणरक्कम",
        waiterName: "वेटरचं नाव",
        date: "तारीख",
        time: "वेळ",
        shareReceipt: "पर्ची सामायिक करा",
        backToTable: "मध्ये परत जा",
        receiptPreview: "पावती पूर्वावलोकन",
        "add": "जोडा",
        "balance": "शिल्लक",
        "selectPaymentMethod": "पेमेंट पद्धत निवडा",
        "addPaymentMethod": "पेमेंट पद्धत जोडा",
        "paymentOptions": "पैसे भरणासाठीचे पर्याय",
        discount: "छूट"

    },

    allOnlineOrder: {
        Pending: "प्रलंबित",
        Accepted: "स्वीकृत",
        InProgress: "प्रगतीत",
        Dispatch: "प्रेषण",
        Delivered: "वितरित",
        Cancelled: "रद्द",
        // Pending: "Pending",
        // Accepted: "Accepted",
        // InProgress: "In-Progress",
        // Dispatch: "Dispatch",
        // Delivered: "Delivered",
        // Cancelled: "Cancelled",
        CustomerName: "ग्राहकाचे नाव शोधा",
        SelectStatus: "स्थिती निवडा",
        Back: "परत",
        OrderId: "ऑर्डर आयडी",
        Date: "दिनांक",
        Customer: "ग्राहक",
        Status: "स्थिती",
        Amount: "रक्कम",
        RejectOrder: "ऑर्डर नाकारणे",
        OrderID: "आदेश कामतत्व ",
        OrderStatus: "आदेश स्थिती ",
        OrderBookingTime: "ऑर्डर बुकिंगची वेळ ",
        Item: "आयटम",
        Discount: "सवलत ",
        ItemPrice: "वस्तूची किंमत ",
        Notes: "नोट्स",
        Addordernoteshere: "येथे ऑर्डर नोट्स जोडा",
        ADD: "जोडा",
        ItemTotal: "एकूण आयटम",
        Delivery: "डिलिव्हरी",
        GrandTotal: "ग्रँड टोटल",
        Customerdetails: "ग्राहक तपशील",
        Name: "नाव:",
        Mobile: "मोबाइल:",
        Address: "पत्ता:",
        City: "शहर:",
        State: "राज्य:",
        Postcode: "पोस्टकोड:",
        Payment: "भुगतान:",
        CurrentStatus: "वर्तमान स्थिति",
        Delivery: "डिलिव्हरी",
        noteOne: "तुमच्याकडे नाही",
        noteTwo: "अधिक ऑर्डर मिळवण्यासाठी तुमच्या स्टोअरची लिंक तुमच्या ग्राहकांसह सोशल मीडियावर शेअर करा.",
        free: "फुकट",
        onlineOrders: "ऑनलाइन ऑर्डर"

    },
    CustomerDetails: {
        search: "ग्राहकाच्या नावाने शोधा",
        addCustomers: "ग्राहकें जोडा +",
        editCustomer: "ग्राहक तपशील संपादित करा",
        customersName: "ग्राहकांचे नाव",
        email: "ईमेल",
        contactNo: "संपर्क नंबर",
        address: "पत्ता",
        city: "शहर",
        country: "देश",
        addCustomer: "ग्राहक जोडा",
        name: "नाव",
        emailAddress: "ईमेल पत्ता",
        mobileNumber: "मोबाइल नंबर",
        submit: "प्रस्तुत करा",
        enterCustomerName: "ग्राहकाचे नाव प्रविष्ट करा",
        enterCustomerEmail: "ग्राहक ईमेल प्रविष्ट करा",
        enterMobileNumber: "मोबाईल नंबर टाका",
        enterAddress: "पत्ता प्रविष्ट करा",
        enterCity: "शहराचे नाव प्रविष्ट करा",
        edit: "संपादन करा",
        delete: "हटवा",
        enterCountry: "आपल्या देशाचे नाव प्रविष्ट करा",
        address: "पत्ता",
        city: "शहर",
        country: "देश",
        customersList: "ग्राहकांची यादी",
        totalCustomerCount: "एकूण ग्राहक संख्या",
        newCustomerCount: "नवीन ग्राहक संख्या",
        customerOftheMonth: "महिन्याचे ग्राहक"
    },

    DiscountDetails: {
        "search": "शोध...",
        "createCoupon": "कूपन तयार करा",
        "discount": "छूट",
        "startDate": "प्रारंभ तारीख",
        "endDate": "शेवटची तारीख",
        Expire: "कालबाह्य",
        "removeDiscount": "छूट हटवा",
        "applyDiscount": "छूट लागू करा",
        "edit": "संपादन करा",
        "delete": "हटवा",
        "submit": "प्रस्तुत करा",
        "addDiscount": "डिस्काउंट जोडा",
        editDiscount: "सवलत संपादित करा",
        "discountName": "डिस्काउंट नाव",
        "discountValue": "डिस्काउंट मूल्य",
        "enterDiscountValue": "डिस्काउंटवेल्यू प्रविष्ट करा",
        "productName": "उत्पादनाचे नांव",
        "beforeDiscount": "छूट पूर्व",
        "afterDiscount": "छूट नंतर",
        "removeDiscountFromProduct": "उत्पादनातून काढा",
        "applyDiscountOnProduct": "उत्पादनावर लागू करा",
        discountTableHeading: "सवलत यादी",
        SearchProductByName: "नावाने उत्पादन शोधा",
        selectedDiscount: "निवडलेली सूट",
        selectCategory: "श्रेणी निवडा",
        RemoveMappedDiscount: "मॅप केलेली सूट काढा",
        SearchDiscountName: "सवलतीच्या नावाने शोधा",

    },
    TaxDetails: {
        search: "शोध...",
        addTax: "कर जोडा +",
        tax: "कर",
        taxes: "करे",
        removeTax: "कर हटवा",
        values: "कर मूल्य",
        applyTax: "कर लागू करा",
        edit: "संपादन करा",
        delete: "हटवा",
        removeTaxFromProduct: "उत्पादनातून कर काढून टाका",
        applyTaxOnProduct: "उत्पादनावर कर लागू करा",
        submit: "प्रस्तुत करा",
        editTax: "कर संपादित करा",
        taxName: "कर नाव",
        taxValueInPercent: "% मध्ये कर मूल्य",
        enterTaxValue: "कर मूल्य प्रविष्ट करा",
        productName: "उत्पादनाचे नांव",
        beforeTax: "कर आधी",
        afterTax: "कर नंतर",
        remove: "काढा",
        apply: "लागू करा",
        taxTableHeading: "करांची यादी",
        selectedTax: "निवडलेला कर ",
        removeMappedTax: "मॅप केलेला कर काढा",
        searchTaxName: "कर नावाने शोधा"

    },
    BrandDetails: {
        "search": "शोध...",
        "brand": "ब्रैंड",
        brandPlaceholder: "ब्रँड नाव प्रविष्ट करा",
        "addBrands": "ब्रँड जोडा +",
        editBrands: "ब्रँड संपादित करा",
        "brandName": "ब्रँड नाव",
        "edit": "संपादन करा",
        "delete": "हटवा",
        "submit": "प्रस्तुत करा",
        brandList: "ब्रँड सूची",
        searchBrandName: "ब्रँड नावाने शोधा"
    },

    UnitDetails: {
        "search": "युनिटच्या नावाने शोधा",
        "unit": "युनिट",
        "addUnit": "युनिट जोडा +",
        "editUnit": "युनिट संपादित करा",
        "unitPlaceholder": "युनिटचे नाव एंटर करा",
        "unitName": "युनिटचे नाव",
        "submit": "प्रस्तुत करा",
        "edit": "संपादन करा",
        "delete": "हटवा",
        "isMeasurable": "दयनीय आहे",
        unitList: "युनिट्सची यादी"
    },
    AllProduct: {
        product: "उत्पाद",
        showExpireBefore: "कालबाह्यता तारीख सेट करा",
        searchProducts: "उत्पादनाच्या नावाने शोधा",
        uploadBulk: "मोठ्या प्रमाणात अपलोड करा",
        addNewProduct: "नवीन उत्पाद जोडा",
        productId: "उत्पादआयडी",
        InventoryManage: "इन्व्हेंटरी व्यवस्थापित करा",
        sellingPrice: "विक्री मूल्य",
        expiryDate: "सक्रियता तारीख",
        Expire: "कालबाह्य",
        status: "स्थिति",
        action: "कार्रवाई",
        availableQuantity: "उपलब्ध प्रमाण",
        fileUpload: "फाइल अपलोड करा",
        lineOne: "कृपया डाउनलोड बटणावर क्लिक करा आणि एक्सेल फाइल डाउनलोड करा",
        lineTwo: "त्यानंतर एक्सेल फाइल संपादित करा आणि आपल्या स्टोअर उत्पादनांची दर अद्यतन करा",
        lineThree: "मूल्य आणि पुन्हा तो अपलोड करा.",
        lineFour: "अपलोड पूर्ण झाल्यानंतर, तुमच्या POS वर जा. क्लिक करा",
        lineFive: "उत्पादन डॅशबोर्डवर जा/सिंक बटण.",
        lineSix: "फक्त xml किंवा xlsm फाइल फॉरमॅट अपलोड करा",
        clickToDownload: "डाउनलोड करण्यासाठी क्लिक करा",
        upload: "अपलोड करा",
        edit: "संपादन करा",
        delete: "हटवा",
        allProducts: "सर्व उत्पादने",
        Back: "परत",
        quantity: "प्रमाण",
        valid: "वैध",
        expired: "कालबाह्य",
        Instock: "स्टॉक मध्ये",
        outofstock: "स्टॉक नाही",
        selectcategory: "श्रेणी निवडा",
        Yes: "होय",
        No: " नाही",
        addQuantity: "मात्रा घाला",
        add: "ॲड",
        addInventory: "सूची जोडा",
        purchasePrice: "खरेदी किंमत",
        enterPurchasePrice: "खरेदी किंमत प्रविष्ट करा",
        purchaseDate: "खरेदीची तारीख",
        notes: "टिप्पण्या",
        enterNotes: "टिप्पण्या प्रविष्ट करा",
        update: "अद्यतन",


    },
    AddNewProduct: {
        productCreation: "उत्पादन निर्मिती",
        productEdit: "उत्पादन संपादन",
        productInformation: "उत्पादन माहिती",
        uploadImage: "चित्र अपलोड करा",
        preview: "पूर्वावलोकन",
        setDefault: "मुलाखती ठरवा",
        notAllowedBeforeUpload: "अपलोड पूर्व अनुमत नाही",
        productName: "उत्पादन नाव",
        enterValidName: "वैध नाव प्रविष्ट करा",
        unit: "उत्पादन युनिट",
        enterValidUnit: "वैध युनिट प्रविष्ट करा",
        addUnit: "युनिट जोडा",
        sellingPrice: "विक्री किंमत",
        productSellingPrice: "उत्पादन विक्री किंमत प्रविष्ट करा",
        productDescription: "उत्पादन वर्णन",
        pleaseEnterProductDescription: "कृपया उत्पादन वर्णन प्रविष्ट करा",
        minimumThreeRows: "किमान 3 पंक्ती",
        purchasingPrice: "खरेदी किंमत",
        mrp: "मूल्य निर्धारण",
        category: "श्रेणी",
        selectCategory: "श्रेणी निवडा",
        addCategory: "श्रेणी जोडा",
        brand: "ब्रँड",
        selectBrand: "ब्रँड निवडा",
        addBrand: "ब्रँड जोडा",
        barcode: "बारकोड",
        inventoryManage: "इन्व्हेंटरी व्यवस्थापन",
        quantity: "प्रमाण",
        expiryDate: "समाप्ती तारीख",
        applyTax: "कर लागू करा",
        selectTax: "कर निवडा",
        addTax: "कर जोडा",
        taxInclude: "कर समाविष्ट करा",
        applyDiscount: "सवलत लागू करा",
        addDiscount: "सवलत जोडा",
        selectDiscount: "सवलत निवडा",
        updateProduct: "उत्पादन अपडेट करा",
        addProduct: "उत्पादन जोडा",
        moreOption: "अधिक पर्याय",
        "hideOption": "पर्याय लपवा",
        productUnit: "उत्पादन युनिट",
        selectUnit: "युनिट निवडा",
        purchasingPriceOfProduct: "उत्पादनाची खरेदी किंमत",
        productMRP: "उत्पादन एमआरपी",
        productBarcode: "उत्पादन बारकोड",
        stockLevelAlert: "स्टॉक लेव्हल अलर्ट",
        submit: "प्रस्तुत करा",
        update: "अद्यतन",
        Back: "परत",
        editInventory: "इन्व्हेंटरी संपादित करा"

    },
    Billing: {
        selectSalesExecutive: "निवडा सेल्स एग्जिक्यूटिव",
        searchProducts: "उत्पादन शोधा...",
        searchSalesExecutive: "विक्री कार्यकारी शोधा...",
        searchCustomer: "ग्राहक शोधा...",
        select: "निवडा",
        expiredProduct: "कालबाह्य झालेले उत्पादन",
        productExpiring: "कालबाह्य होणारे उत्पादन",
        applyDiscount: "डिस्काऊंट लागू करा",
        productExpiryClickHere: "उत्पादन समाप्तीसाठी येथे क्लिक करा",
        productName: "उत्पादनाचे नाव",
        mrp: "एमआरपी",
        sellingPrice: "विक्री मूल्य",
        price: "मूल्य",
        quantity: "प्रमाण",
        remove: "काढा",
        emptyCart: "रिक्त कार्ट",
        customer: "ग्राहक",
        change: "बदल",
        salesExecutive: "सेल्स एग्जिक्यूटिव",
        tax: "कर",
        discount: "डिस्काउंट",
        applyAdditionalDiscount: "अतिरिक्त डिस्काऊंट लागू करा",
        flateDiscount: "फ्लैट डिस्काउंट",
        total: "एकूण",
        fastPay: "झटपट भरा",
        selectCustomer: "ग्राहक निवडा",
        selectDiscount: "सवलत निवडा",
        afterDiscount: "छूट नंतर",
        selectPaymentMode: "पेमेंट मोड निवडा",
        putOnHold: "होल्ड वर ठेवा",
        submit: "प्रस्तुत करा",
        edit: "संपादन करा",
        delete: "हटवा",
        clearCart: "कार्ट साफ करा",
        paymentSuccess: "पेमेंट यशस्वी!",
        customerName: "ग्राहकाचे नाव",
        orderId: "ऑर्डर आयडी",
        totalAmount: "एकूण रक्कम",
        paymentType: "पैसे भरण्याची पध्दत",
        pullBack: "परत खेचणे",
        save: "जतन करा",
        sendToKOT: "KOT ला पाठवा",
        item: "आयटम",
        table: "टेबल",
        removeTable: "टेबल काढा",
        products: "उत्पादने",
        chooseCategory: "श्रेणी निवडा"

    },
    FloorDetails: {
        search: "मजल्याच्या नावाने शोधा",
        addFloor: "मजला जोडा +",
        editFloor: "मजला संपादित करा",
        name: "नाव",
        location: "स्थान",
        tableCount: "मेज़ची संख्या",
        date: "तारीख",
        edit: "संपादित करा",
        delete: "हटवा",
        submit: "प्रस्तुत करा",
        namePlaceholder: "तलाचं नाव प्रविष्ट करा",
        locationPlaceholder: "स्थानाचं नाव प्रविष्ट करा",
        floorPlan: "फ्लोर प्लान",
        editFloorPlan: "फ्लोर प्लान संपादित करा",
        height: "उच्ची",
        width: "रुंदी",
        noOfSeats: "कुर्सीची संख्या:",
        floorList: "मजल्याची यादी"

    },
    TableDetails: {
        search: "टेबल नावाने शोधा",
        addTable: "मेज जोडा +",
        editTable: "मेज संपादित करा",
        tableName: "मेजचं नाव",
        capacity: "मेजची क्षमता",
        date: "तारीख",
        edit: "संपादित करा",
        delete: "हटवा",
        submit: "प्रस्तुत करा",
        selectFloor: "तल निवडा",
        tableNamePlaceholder: "मेजचं नाव",
        capacityPlaceholder: "मेजची क्षमता प्रविष्ट करा",
        tableList: "मेज सूची"
    },
    StockDashboard: {
        poNumber: "PO क्रमांक",
        status: "स्थिती",
        updated: "सुधारित",
        expectedOn: "प्रत्याशित दिवस",
        vendor: "विक्रेता",
        destination: "गंतव्य",
        amount: "रक्कम",
        actions: "क्रियाएं",
        notes: "टीप",
        productName: "उत्पादनाचे नाव",
        purchasingPrice: "खरेदी किंमत",
        lastUpdated: "शेवटचे अद्यतन",
        quantity: "प्रमाण",
        inventoryId: "सूची क्रमांक"
    },
    PurchaseOrderPage: {
        vendor: "विक्रेता",
        vendorPlaceholder: "विक्रेता निवडा",
        shipTo: "शिप टू",
        shipToPlaceholder: "निवडा",
        poNumber: "PO क्रमांक",
        poInvoiceNumber: "PO चालान क्रमांक",
        expectedDelivery: "अपेक्षित वितरण",
        billingDate: "बिलिंग तारीख",
        applyTaxAfterDiscount: "सवारी के बाद कर लागू करें",
        notes: "टिप्पणियाँ",
        addItem: "आइटम जोडा",
        srNo: "क्रमांक",
        productName: "उत्पाद का नाम",
        unitBuyingPrice: "यूनिट खरीद मूल्य",
        unitBasePrice: "यूनिट बेस मूल्य",
        unitSellingPrice: "यूनिट विक्रय मूल्य",
        unitBasePriceWithoutTax: "यूनिट बेस मूल्य (कर के बिना)",
        unitBuyingPriceWithTax: "यूनिट खरीद मूल्य (कर सहित)",
        mrp: "MRP",
        quantity: "मात्रा",
        discount: "छूट",
        tax: "कर",
        actions: "क्रियाएं",
        calculateUnitBuyingPrice: "यूनिट खरीद मूल्य की गणना करें",
        discountType: "छूट प्रकार",
        discountValue: "छूट मूल्य",
        percentage: "प्रतिशत",
        flat: "समतल",
        namePlaceholder: "उत्पाद निवडा",
        taxPlaceholder: "कर निवडा",
        discountPlaceholder: "प्रकार निवडा",
        createItem: "आइटम बनवा",
        submit: "प्रस्तुत करा",
        poNumberPlaceholder: 'पीओ नंबर प्रविष्ट करा',
        poInvoicePlaceholder: 'पीओ इनवॉइस नंबर प्रविष्ट करा'
    },
    AccountAndSettings: {
        posSetting: "POS सेटिंग",
        invoiceSettings: "चालान सेटिंग्स",
        invoiceSize: "चालान का आकार",
        preview: "पूर्वावलोकन",
        sizePlaceholder: "चालान का आकार निवडा"
    },
    CategoryDetails: {
        "search": "श्रेणी नावाने शोधा",
        "addCategory": "+ श्रेणी जोडा",
        "editCategory": "श्रेणी संपादित करा",
        "category": "श्रेणी",
        "inputText": "श्रेणीसाठी येथे टाइप करा",
        "submit": "प्रस्तुत करा",
        "edit": "संपादन करा",
        "delete": "हटवा",
        categoryList: "श्रेणी यादी"
    },

    SalesExecutive: {
        search: "विक्री कार्यकारी नावाने शोधा",
        addSalesExecutive: "+ सेल्स एक्झिक्युटिव्ह जोडा",
        salesExecutive: "सेल्स एक्झिक्युटिव्ह",
        activeInactive: "सक्रिय/निष्क्रिय",
        active: "सक्रिय",
        inactive: "निष्क्रिय",
        setOnDuty: "ड्युटीवर सेट",
        addSalesExecutiveName: "विक्री कार्यकारी नाव जोडा",
        salesExecutiveName: "विक्री कार्यकारी नाव",
        editSalesExecutiveName: "विक्री कार्यकारी नाव संपादित करा",
        enterSalesExecutiveName: "विक्री कार्यकारी नाव प्रविष्ट करा",
        edit: "संपादन करा",
        delete: "हटवा",
        submit: "प्रस्तुत करा",
        salesExcutiveList: "विक्री कार्यकारी यादी"
    },
    StoreSetting: {
        storeDetails: "स्टोअर तपशील",
        storeName: "स्टोअरचे नाव",
        storeId: "स्टोर आईडी",
        currency: "मुद्रा",
        gst: "जीएसटी",
        deliveryDetails: "होम डिलिव्हरी",
        homeDelivery: "घरपोच",
        minimumOrderLimit: "न्यूनतम ऑर्डर सीमा",
        freeDeliveryWithin: "मुक्त डिलिव्हरी",
        storeTiming: "स्टोर उघडण्याचे वेळ",
        storeOpeningTime: "स्टोर उघडण्याचा वेळ",
        storeClosingTime: "स्टोर बंद करण्याचा वेळ",
        storeCloseDay: "स्टोर बंद दिवस",
        address: "पत्ता",
        area: "क्षेत्र",
        city: "शहर",
        pincode: "पिन कोड",
        latitude: "अक्षांश",
        longitude: "देशांतर",
        contact: "संपर्क",
        mobile: "मोबाइल",
        emailId: "ईमेल आयडी",
        customerID: "ग्राहक आयडी",
        editStore: "स्टोर संपादित करा",
        licenseDetails: "लायसेंस तपशील",
        licenseKey: "लायसेंस की",
        status: "स्थिती",
        expiryDate: "समाप्ती तारीख",
        remainigDate: "शेष दिवस"
    },
    StoreEdit: {
        storeInformation: "दुकान माहिती",
        storeId: "दुकान आयडी",
        storeName: "दुकान नाव",
        currency: "करेंसी",
        gst: "जीएसटी",
        deliveryDetails: "डिलिव्हरीची माहिती",
        minimumOrderLimit: "कमीत कमी ऑर्डर सीमा",
        deliveryCharge: "डिलिव्हरी चार्ज",
        freeDeliveryWithin: "जरी कर डिलिव्हरी",
        storeTiming: "दुकानचे वेळ",
        storeOpeningTime: "दुकान उघडण्याचा वेळ",
        storeClosingTime: "दुकान बंद करण्याचा वेळ",
        storeCloseDay: "स्टोर बंद दिवस",
        address: "पत्ता",
        city: "शहर",
        pincode: "पिनकोड",
        latitude: "अक्षांश",
        longitude: "देशांतर",
        area: "क्षेत्र",
        changeAddress: "पत्ता बदला",
        updateStore: "दुकान अपडेट करा",
        mapAddress: "तुमचे दुकान ऑनलाइन सेट करण्यासाठी आम्हाला तुमच्या दुकानाचा पत्ता हवा आहे",
        next: "पुढे",
        back: "मागे",
        areaField: "क्षेत्रफळ",
        homeDeliveryAvailable: "होम डिलिव्हरी उपलब्ध",
        cancel: "रद्द"
    },
    addStore: {
        "AddStore": "दुकान जोडा",
        "AddressConfirmation": "पत्ता पुष्टीकरण",
        "ShopNo": "दुकान क्रमांक, लेन क्रमांक, इमारत क्रमांक इत्यादी",
        // "Selectedaddressonmap": "नकाशे पर चयनित पत्ता",
        "Selectedaddressonmap": "पत्ता",
        "State": "राज्य",
        "Pincode": "पिन कोड",
        "Country": "देश",
        "USETHISADDRESS": "या पत्ता वापरा",
        "StoreSummary": "दुकान सारांश",
        "StoreName": "दुकानाचे नाव",
        "StoreCategory": "दुकान श्रेणी",
        "StoreCurrency": "दुकान मुद्रा",
        "StoreAddress": "दुकान पत्ता",
        "CREATESTORE": "दुकान तयार करा",
        "City": "शहर",
        "EnterStoreName": "दुकानाचं नाव टाका",
        "SelectCountry": "देश निवडा",
        "SelectStoreType": "दुकानाचा प्रकार निवडा",
        "ChooseAddressUsingMap": "नकाशाचा वापर करून पत्ता निवडा",
        "NEXT": "पुढे जा",
        "Back": "मागे",
        "Mobile": "मोबाईल",
        "mobileplaceholder": "कृपया मोबाईल नंबर टाका",
        "StoreNotes": "आम्हाला तुमच्याकडून काही तपशीलांची आवश्यकता आहे जेणेकरून तुम्ही या आश्चर्यकारक अॅपसह प्रारंभ करू शकता.",
        "WelcomeNotes": "Ezy POS मध्ये आपले स्वागत आहे",
    },
    Report: {
        selectCustomDate: "कस्टम तारीख निवडा",
        search: "शोध...",
        selectMonth: "महिना निवडा",
        getReport: "अहवाल प्राप्त करा",
        date: "तारीख",
        total: "एकूण",
        details: "तपशील",
        startDate: "सुरुवात तारीख",
        endDate: "अंतिम तारीख",
        emptyPageNote: "कृपया अहवाल तारीख किंवा महिना निवडा",
        showChart: "चार्ट दाखवा",
        reportTransactionChart: "अहवाल व्यवहार चार्ट",
        customer: "ग्राहक",
        paymentMode: "भुगतान पद्धती",
        paymentId: "भुगतान आयडी",
        viewOrder: "ऑर्डर पहा",
        products: "उत्पादने",
        quantity: "प्रमाण",
        discount: "डिस्काउंट",
        tax: "कर",
        transactionsReportDetails: "व्यवहार अहवाल तपशील"
    },
    Transaction: {
        "transactionPleaseSelectDate": "व्यवहार कृपया तारीख निवडा",
        "search": "व्यवहार शोधा",
        "date": "तारीख",
        "selectCustomDate": "कस्टम तारीख निवडा",
        "paymentType": "पैसे भरण्याची पध्दत",
        "servedBy": "यांनी सेवा दिली",
        "paymentId": "पेमेंट आयडी",
        "customer": "ग्राहक",
        "total": "एकूण",
        "endDate": "अंतिम तारीख",
        "startDate": "सुरुवात तारीख",
        "find": "find",
        "today": "आज",
        "last7Days": "शेवटचे ७ दिवस",
        "last30Days": "शेवटचे ३० दिवस",
        "last3Month": "गेल्या ३ महिन्यात",
        "last6Month": "गेल्या ६ महिन्यात",
        "transactionInLast": "व्यवहार शेवटी",
        "transactionDetails": "व्यवहाराचा तपशील",
        "selectMonth": "महिना निवडा",
        "transaction": "व्यवहार",
        transactionList: "व्यवहार यादी",
        selectSalesExecutive: "सेल्स एक्झिक्युटिव्ह निवडा"

    },

    SingleTransaction: {
        "products": "उत्पादने",
        "quantity": "प्रमाण",
        "total": "एकूण",
        "tax": "कर",
        "discount": "सवलत"
    },

    trailNotification: {
        ThereAre: "तुमच्या पायावर",
        leftOnYourTrail: "उरलेले आहेत.",
        clickHereToUpgrade: "अपग्रेड करण्यासाठी येथे क्लिक करा",
        UpgradeToUnlockThisFeature: "ही सुविधा अनलॉक करण्यासाठी अपग्रेड करा",
        Upgrade: "अपग्रेड",
        day: "दिवस",
        days: "दिवस",
        freeTrialPlan: "मोफत चाचणी योजना"
    }

};

export default translation
